## Vector Linear Combinations

Let $ \{ \textbf{v}_1, \ \textbf{v}_2, \ \cdots \, \textbf{v}_p \} $ be vectors in $ \mathbb{R}^n $. A vector $ \textbf{b} $ is said to be a linear combination of the vectors $ \{ \textbf{v}_1, \ \textbf{v}_2, \ \cdots, \ \textbf{v}_p \} $ if there exists scalars $ x_1, x_2, \cdots, x_p $ such that 

$ x_1 \textbf{v}_1 + x_2 \textbf{v}_2 + \cdots + x_p \textbf{v}_p = \textbf{b} $.

### Linear Combination Problem

Given vectors $ \textbf{v}_1, \cdots, \textbf{v}_p $ and $ \textbf{b} $. Is $ \textbf{b} $ a linear combination of $ \textbf{v}_1, \cdots, \textbf{v}_p $ ?

The problem of determining if a given vector $ \textbf{b} $ is a linear combination of the vectors $ \textbf{v}_1, \textbf{v}_2, \cdots, \textbf{v}_p $ is equivalent to solving the linear system of equations with augmented matrix

$ [ \textbf{A} \ \ \textbf{b} ] = [ \textbf{v}_1 \ \ \textbf{v}_2 \ \ \cdots \ \ \textbf{v}_p \ \ \textbf{b} ] $

This provides for three possibilities:

- If the linear system is inconsistent, then $ \textbf{b} $ is not a linear combination of $ \textbf{v}_1, \textbf{v}_2, \cdots, \textbf{v}_p $
  
  In this case there doesn't exist scalars $ x_1, x_2, \cdots, x_p $ such that $ x_1 \textbf{v}_1 + x_2 \textbf{v}_2 + \cdots + x_p \textbf{v}_p = \textbf{b} $

- If the linear system is consistent and the solution is unique, then $ \textbf{b} $ can be written as a linear combination of $ \textbf{v}_1, \textbf{v}_2, \cdots, \textbf{v}_p $ in only one way

- If the linear system is consistent and the solution has free parameters, then $ \textbf{b} $ can be written as a linear combination of $ \textbf{v}_1, \textbf{v}_2, \cdots, \textbf{v}_p $ in infinitely many ways

### Example 1

Is the vector $ \textbf{b} $ a linear combination of vectors $ \textbf{v}_1 $ and $ \textbf{v}_2 $ ?

$ 
\textbf{b} = 
\begin{bmatrix}
7 \\
4 \\
-3 
\end{bmatrix}
\ \ \ \
\textbf{v}_1 =
\begin{bmatrix}
1 \\
-2 \\
-3
\end{bmatrix}
\ \ \ \
\textbf{v}_2 =
\begin{bmatrix}
\ 2 \ \\
\ 5 \ \\
\ 6 \
\end{bmatrix}
$

Solution:

We need to find $ x_1 $ and $ x_2 $ such that 

$ \textbf{b} = x_1 \textbf{v}_1 + x_2 \textbf{v}_2 $

Start by forming the augmented matrix $ [\textbf{v}_1\ \ \  \textbf{v}_2 \ \ \ \textbf{b}] $ then finding its RREF form

$ 
[\textbf{v}_1 \ \ \ \textbf{v}_2 \ \ \ \textbf{b}] 
     =
\begin{bmatrix}
1 & 2 & | & 7\\
-2 & 5 & | & 4\\
-5 & 6 & | & -3
\end{bmatrix}
$

In [3]:
import numpy as np
from sympy import Matrix

A = np.array([[1, 2, 7], [-2, 5, 4], [-5, 6, -3]]);

# Convert to sympy matrix
Mat = Matrix(A)

# Get RREF (Reduced Row Echelon Form)
RREF = Mat.rref()[0]

print(np.array(RREF))

[[1 0 3]
 [0 1 2]
 [0 0 0]]


in augmented matrix form

$
A =
\begin{bmatrix}
1 & 0 & | & 3 \\
0 & 1 & | & 2 \\
0 & 0 & | & 0 
\end{bmatrix}
$

$
\implies x_1 = 3, \ \ \ \ x_2 = 2
$

Therefore $ \textbf{b} $ a linear combination of vectors $ \textbf{v}_1 $ and $ \textbf{v}_2 $

$
\textbf{b} = 3
\begin{bmatrix}
1 \\
-2 \\
-3
\end{bmatrix}
    + 2
\begin{bmatrix}
2 \\
5 \\
6
\end{bmatrix}
    =
\begin{bmatrix}
7 \\
4 \\
-3 
\end{bmatrix}
$

### Example 2

Is the vector $ \textbf{b} $ a linear combination of vectors $ \textbf{v}_1 $, $ \textbf{v}_2 $ and $ \textbf{v}_3 $ ?

$ 
\textbf{b} = 
\begin{bmatrix}
8 \\
8 \\
12 
\end{bmatrix}
\ \ \ \
\textbf{v}_1 =
\begin{bmatrix}
2 \\
1 \\
3
\end{bmatrix}
\ \ \ \
\textbf{v}_2 =
\begin{bmatrix}
\ 4 \ \\
\ 2 \ \\
\ 6 \
\end{bmatrix}
\ \ \ \
\textbf{v}_3 =
\begin{bmatrix}
\ 6 \ \\
\ 4 \ \\
\ 9 \
\end{bmatrix}
$

We are looking for $ x_1 $, $ x_2 $ and $ x_3 $ such that 

$ \textbf{b} = x_1 \textbf{v}_1 + x_2 \textbf{v}_2 + x_3 \textbf{v}_3 $

Solution:

Construct the augmented matrix $ [\textbf{v}_1\ \ \  \textbf{v}_2 \ \ \ \textbf{v}_3 \ \ \ \textbf{b}] $

$ 
[\textbf{v}_1 \ \ \ \textbf{v}_2 \ \ \ \textbf{v}_3 \ \ \ \textbf{b}] 
     =
\begin{bmatrix}
2 & 4 & 6 & | & 8 \\
1 & 2 & 4 & | & 8 \\
3 & 6 & 9 & | & 12
\end{bmatrix}
$

Convert to RREF form

In [4]:
import numpy as np
from sympy import Matrix

A = np.array([[2, 4, 6, 8], [1, 2, 4, 8], [3, 6, 9, 12]]);

# Convert to sympy matrix
Mat = Matrix(A)

# Get RREF (Reduced Row Echelon Form)
RREF = Mat.rref()[0]

print(np.array(RREF))

[[1 2 0 -8]
 [0 0 1 4]
 [0 0 0 0]]


Therefore we get

$ 
\begin{bmatrix}
1 & 2 & 0 & | & -8 \\
0 & 0 & 1 & | & 4 \\
0 & 0 & 0 & | & 0
\end{bmatrix}
$

$ \implies x_3 = 4 \ \ $ 

and 

$ x_1 + 2 x_2 = -8 \implies x_1 = - 2 x_2 -8 $

So $ x_2 $ is a free variable, so we can have multiple values of $ x_1 $, $ x_2 $ and $ x_3 $ 

**a)** If $ x_2 = 1 \implies x_1 = -10 $ and $ x_3 = 4 $ is fixed

$ 
\implies 
\textbf{b} = -10
\begin{bmatrix}
2 \\
1 \\
3 
\end{bmatrix}
    + 
\begin{bmatrix}
4 \\
2 \\
6 
\end{bmatrix}
+4
\begin{bmatrix}
6 \\
4 \\
9 
\end{bmatrix}
    =
\begin{bmatrix}
8 \\
8 \\
12 
\end{bmatrix}
$

**b)** If $ x_2 = -2 \implies x_1 = -4 $ and $ x_3 = 4 $ is fixed

$ 
\implies 
\textbf{b} = -4
\begin{bmatrix}
2 \\
1 \\
3 
\end{bmatrix}
    -2 
\begin{bmatrix}
4 \\
2 \\
6 
\end{bmatrix}
+4
\begin{bmatrix}
6 \\
4 \\
9 
\end{bmatrix}
    =
\begin{bmatrix}
8 \\
8 \\
12 
\end{bmatrix}
$

**c)** In general, we can write

$ 
\implies 
\textbf{b} = (-2t-8)
\begin{bmatrix}
2 \\
1 \\
3 
\end{bmatrix}
    +t 
\begin{bmatrix}
4 \\
2 \\
6 
\end{bmatrix}
+4
\begin{bmatrix}
6 \\
4 \\
9 
\end{bmatrix}
    =
\begin{bmatrix}
8 \\
8 \\
12 
\end{bmatrix}
$

## Span

Let $ \{ \textbf{v}_1, \textbf{v}_2, \cdots, \textbf{v}_p \} \in \mathbb{R}^n $ be vectors. The set of all vectors that are a linear combination of $ \{ \textbf{v}_1, \textbf{v}_2, \cdots, \textbf{v}_p \} $ is called the span of $ \{ \textbf{v}_1, \textbf{v}_2, \cdots, \textbf{v}_p \} $, and is denoted as 

$ S = span\{\textbf{v}_1, \textbf{v}_2, \cdots, \textbf{v}_p\} $

If $ \textbf{b} \in span\{\textbf{v}_1, \textbf{v}_2, \cdots, \textbf{v}_p\} $ then $ \textbf{b} $ is a linear combination of $ \{ \textbf{v}_1, \textbf{v}_2, \cdots, \textbf{v}_p \} $. This implies there are scalars $ x_1, x_2, ..., x_n $ such that 

$ \textbf{b} = x_1 \textbf{v}_1 + x_2 \textbf{v}_2 + ··· + x_p \textbf{v}_p $

### Example 1

Given the vectors $ \textbf{v}_1 $, $ \textbf{v}_2 $ and $ \textbf{b} $ shown below. 

Is the vector $ \textbf{b} $ in the span of the vectors $ \textbf{v}_1 $ and $ \textbf{v}_2 $, or $ \textbf{b} \in span\{\textbf{v}_1, \textbf{v}_2\} $

$ 
\textbf{b} = 
\begin{bmatrix}
7 \\
4 \\
-3 
\end{bmatrix}
\ \ \ \
\textbf{v}_1 =
\begin{bmatrix}
1 \\
-2 \\
-5
\end{bmatrix}
\ \ \ \
\textbf{v}_2 =
\begin{bmatrix}
\ 2 \ \\
\ 5 \ \\
\ 6 \
\end{bmatrix}
$

Solution:

$ \textbf{b} \in span\{\textbf{v}_1, \textbf{v}_2\} $ if $ \textbf{b} $ can be expressed as a linear combination of $\{\textbf{v}_1, \textbf{v}_2\} $ i.e. there exists scalars $ x_1 $ and $ x_2 $ such that

$ x_1 \textbf{v}_1 + x_2 \textbf{v}_2 = \textbf{b} $

We have already evaluated this in Example 1 of Linear Combinations section

$
\textbf{b} = 3
\begin{bmatrix}
1 \\
-2 \\
-3
\end{bmatrix}
    + 2
\begin{bmatrix}
2 \\
5 \\
6
\end{bmatrix}
    =
\begin{bmatrix}
7 \\
4 \\
-3 
\end{bmatrix}
$

Therefore $ \textbf{b} \in span\{\textbf{v}_1, \textbf{v}_2\} $

### Example 2

Is the vector $ \textbf{b} $ in the span of the vectors $ \textbf{v}_1 $, $ \textbf{v}_2 $ and $ \textbf{v}_3 $, or $ \textbf{b} \in span\{\textbf{v}_1, \textbf{v}_2, \textbf{v}_3\} $

$ 
\textbf{b} = 
\begin{bmatrix}
8 \\
8 \\
12 
\end{bmatrix}
\ \ \ \
\textbf{v}_1 =
\begin{bmatrix}
2 \\
1 \\
3
\end{bmatrix}
\ \ \ \
\textbf{v}_2 =
\begin{bmatrix}
\ 4 \ \\
\ 2 \ \\
\ 6 \
\end{bmatrix}
\ \ \ \
\textbf{v}_3 =
\begin{bmatrix}
\ 2 \ \\
\ 1 \ \\
\ 4 \
\end{bmatrix}
$

Solution:

$ \textbf{b} \in span\{\textbf{v}_1, \textbf{v}_2, \textbf{v}_3\} $ if $ \textbf{b} $ can be expressed as a linear combination of $\{\textbf{v}_1, \textbf{v}_2, \textbf{v}_3\} $ i.e. there exists scalars $ x_1 $, $ x_2 $ and $ x_3 $ such that

$ \textbf{b} = x_1 \textbf{v}_1 + x_2 \textbf{v}_2 + x_3 \textbf{v}_3 $

We have already evaluated this in Example 2 of Linear Combinations section

$ 
\implies 
\textbf{b} = (-2t-8)
\begin{bmatrix}
2 \\
1 \\
3 
\end{bmatrix}
    +t 
\begin{bmatrix}
4 \\
2 \\
6 
\end{bmatrix}
+4
\begin{bmatrix}
6 \\
4 \\
9 
\end{bmatrix}
    =
\begin{bmatrix}
8 \\
8 \\
12 
\end{bmatrix}
$

Therefore $ \textbf{b} \in span\{\textbf{v}_1, \textbf{v}_2, \textbf{v}_3\} $

### Example 3

The vectors $ \textbf{u} $, $ \textbf{v} $ and $ \textbf{w} $ are defined below. Show that $ \textbf{w} $ is in $ span\{ \textbf{u}, \textbf{v} \} $ 

$ 
\textbf{u} = 
\begin{bmatrix}
1 \\
1 \\
0 
\end{bmatrix}
,\ \ \ \
\textbf{v} =
\begin{bmatrix}
3 \\
2 \\
0
\end{bmatrix}
,\ \ \ \ 
\textbf{w} = 
\begin{bmatrix}
4 \\
5 \\
0 
\end{bmatrix}
$

Solution: 

For a vector to be in $ span\{ \textbf{u}, \textbf{v} \} $, it must be a linear combination of these vectors.

If $ \textbf{w} \in span\{ \textbf{u}, \textbf{v} \} $, we must be able to find scalars $ a $ and $ b $ such that 

$ \textbf{w} = a \textbf{u} + b \textbf{v} $ 

Writing this matrix form

$ 
\begin{bmatrix}
4 \\
5 \\
0 
\end{bmatrix}
    =
a
\begin{bmatrix}
1 \\
1 \\
0
\end{bmatrix}
    b 
\begin{bmatrix}
3 \\
2 \\
0 
\end{bmatrix}
$

To solve, write this as a system of linear equations

$
\begin{bmatrix}
1 & 3 \\
1 & 2 
\end{bmatrix}
\begin{bmatrix}
a \\
b 
\end{bmatrix}
    = 
\begin{bmatrix}
4 \\
5  
\end{bmatrix}
$

To solve this we can express the matrix in RREF or calculate the inverse matrix. 

In [4]:
import numpy as np
import scipy as sp
from sympy import Matrix


# create the matrix
A = np.array([[1, 3, 4], [1, 2, 5]]);

# Convert to sympy matrix
A_Mat = Matrix(A)

# find RREF (Reduced Row Echelon Form)
RREF = A_Mat.rref()[0]

print(np.array(RREF), '\n')

[[1 0 7]
 [0 1 -1]] 



The RREF results means $ a = 7 $ and $ b = -1 $

Therefore, 

$ \textbf{w} = 7 \textbf{u} - \textbf{v} $

We can also evaluate the inverse matrix

$
\begin{bmatrix}
a \\
b 
\end{bmatrix}
    =
\begin{bmatrix}
1 & 3 \\
1 & 2 
\end{bmatrix}^{-1} 
\begin{bmatrix}
4 \\
5  
\end{bmatrix}
$

In [6]:
import numpy as np
import scipy as sp


# create the matrix
A = np.array([[1, 3,], [1, 2]]);


# find inverse using scipy
print(sp.linalg.inv(A))

[[-2.  3.]
 [ 1. -1.]]


$
\begin{bmatrix}
a \\
b 
\end{bmatrix}
    =
\begin{bmatrix}
-2 & 3 \\
1 & -1 
\end{bmatrix} 
\begin{bmatrix}
4 \\
5  
\end{bmatrix}
$

This means

$ a = -8 + 15 = 7 $ and $ b = 4 - 5 = -1 $ 

with the same result

$ \textbf{w} = 7 \textbf{u} - \textbf{v} $

## Linear Independence

- The set of vectors $ \{\textbf{v}_1, \textbf{v}_2, ... , \textbf{v}_n\} $ is linearly independent if and only if $ \textbf{0} $ can be written in only one way as a linear combination of $ \{\textbf{v}_1, \textbf{v}_2, ..., \textbf{v}_n\} $. In other words, if 
  
  $ t_1\textbf{v}_1 + t_2 \textbf{v}_2 + ···+ t_n \textbf{v}_n = \textbf{0} $ 
  
  then necessarily the coefficients $ t_1, t_2, ..., t_n $ are all zero.
  
- A set of vectors $ \{\textbf{v}_1, \textbf{v}_2, ..., \textbf{v}_n\} $ is said to be linearly dependent if some $ \textbf{v}_j $ can be written as a linear combination of the other vectors, that is, if $ \textbf{v}_j \in span\{ \textbf{v}_1, ..., \textbf{v}_{j−1}, \textbf{v}_{j+1}, ..., \textbf{v}_n \} $. 

  If $ \textbf{v}_1, \textbf{v}_2, ..., \textbf{v}_n $ is not linearly dependent then we say that $ \textbf{v}_1, \textbf{v}_2, ..., \textbf{v}_n $ is linearly independent.

- The set $ \{\textbf{v}_1, \textbf{v}_2, ..., \textbf{v}_n\} $ is linearly independent if and only if the the rank of $ \textbf{A} $ is $ r = n $, that is, if the number of leading entries $ r $ in the REF (or RREF) of $ \textbf{A} $ is exactly $ n $.

### Example 1

Show the following vectors are linearly dependent 

$ 
\textbf{v}_1 =
\begin{bmatrix}
\ 1 \ \\
\ 2 \ \\
\ 3 \
\end{bmatrix}
\ \ \ \
\textbf{v}_2 =
\begin{bmatrix}
\ 4 \ \\
\ 5 \ \\
\ 6 \
\end{bmatrix}
\ \ \ \
\textbf{v}_3 =
\begin{bmatrix}
\ 2 \ \\
\ 1 \ \\
\ 0 \
\end{bmatrix}
$

Solution: 

Since a vector is linearly dependent if it can be written as a linear combination of the other vectors in the same set $ \textbf{v}_j \in span\{ \textbf{v}_1, ..., \textbf{v}_{j−1}, \textbf{v}_{j+1}, ..., \textbf{v}_n \} $. We simply need to show one of the vectors can be set as a linear combination of the other vectors.

We can visually see that

$ 
\textbf{v}_2 = 2\textbf{v}_1 + \textbf{v}_3
    = 2  
\begin{bmatrix}
\ 1 \ \\
\ 2 \ \\
\ 3 \
\end{bmatrix}
+
\begin{bmatrix}
\ 2 \ \\
\ 1 \ \\
\ 0 \
\end{bmatrix}
    =
\begin{bmatrix}
\ 4 \ \\
\ 5 \ \\
\ 6 \
\end{bmatrix}    
$

Therefore, since $ \textbf{v}_2 \in span \{ \textbf{v}_1, \textbf{v}_3 \} $ then the vectors $ \{ \textbf{v}_1, \textbf{v}_2, \textbf{v}_3 \} $ are linearly dependent

### Example 2

Verify whether the set $ \{ \textbf{u}, \textbf{v}, \textbf{w} \} $ is linearly independent.

$ 
\textbf{u} =
\begin{bmatrix}
\ 1 \ \\
\ 1 \ \\
\ 0 \
\end{bmatrix}
\ \ \ \
\textbf{v} =
\begin{bmatrix}
\ 1 \ \\
\ 0 \ \\
\ 1 \
\end{bmatrix}
\ \ \ \
\textbf{v} =
\begin{bmatrix}
\ 0 \ \\
\ 1 \ \\
\ 1 \
\end{bmatrix}
$

**Solution :**

Suppose we have a linear combination 

$ a \textbf{u} + b \textbf{v} + c \textbf{w} = \textbf{0} $

We need to show that this is only true if $ a=0 $, $ b=0 $ and $ c=0 $

We do this by forming this column matrix

$
A = 
\begin{bmatrix}
1 & 1 & 0 \\
1 & 0 & 1 \\
0 & 1 & 1 
\end{bmatrix}
$

and show that $ \textbf{Ax} = \textbf{0} $

only has the trivial solution.

In [1]:
import numpy as np
import scipy as sp


# create the matrix
A = np.array([[1, 1, 0], [1, 0, 1], [0, 1, 1]]);


# find inverse using scipy
print(sp.linalg.inv(A))

[[ 0.5  0.5 -0.5]
 [ 0.5 -0.5  0.5]
 [-0.5  0.5  0.5]]


### The maximum size of a linearly independent set

Let $ \textbf{v}_1, \textbf{v}_2, ..., \textbf{v}_p $ be a set of vectors in $ \mathbb{R}^n $. If $ p > n $ then $ \textbf{v}_1, \textbf{v}_2, ..., \textbf{v}_p $ are linearly dependent. Equivalently, if the vectors $ \textbf{v}_1, \textbf{v}_2, ..., \textbf{v}_p $ in $ \mathbb{R}^n $ are linearly independent then $ p ≤ n $.

## Bases Vectors

Let $ W $ be a subspace of a vector space $ V $. 

A set of vectors $ B = \{\textbf{v}_1, \cdots , \textbf{v}_k\} \in W $ is said to be a basis for $ W $ if 

- The set $ B $ spans all of $ W $, that is, $ W = span\{\textbf{v}_1, \cdots, \textbf{v}_k\} $, and
  
- The set $ B $ is linearly independent.

### Example 1

Show the standard unit vectors form a basis for $ V = \mathbb{R}^3 $

$ 
\textbf{e}_1 = 
\begin{bmatrix}
1 \\
0 \\
0 
\end{bmatrix}
\ \ \ \
\textbf{e}_2 =
\begin{bmatrix}
0 \\
1 \\
0
\end{bmatrix}
\ \ \ \
\textbf{e}_3 =
\begin{bmatrix}
\ 0 \ \\
\ 0 \ \\
\ 1 \
\end{bmatrix}
$

Solution:

Any vector $ x \in \mathbb{R}^3 $ can be written as a linear combination $ \textbf{e}_1, \textbf{e}_2, \textbf{e}_3 $

$ 
\textbf{x} =
\begin{bmatrix}
x_1 \\
x_2 \\
x_3 
\end{bmatrix}
    =
x_1
\begin{bmatrix}
1 \\
0 \\
0 
\end{bmatrix}
+
x_2
\begin{bmatrix}
0 \\
1 \\
0
\end{bmatrix}
+
x_3
\begin{bmatrix}
\ 0 \ \\
\ 0 \ \\
\ 1 \
\end{bmatrix}
    =
x_1 \textbf{e}_1 + x_2 \textbf{e}_2 + x_3 \textbf{e}_3
$

Therefore, $ span\{\textbf{e}_1, \textbf{e}_2, \textbf{e}_3 \} = \mathbb{R}^3 $ and the set $ B = \{\textbf{e}_1, \textbf{e}_2, \textbf{e}_3\} $ is linearly independent.

Therefore the bases vectors $ \textbf{e}_1, \textbf{e}_2, \textbf{e}_3 $ form a bases for $ \mathbb{R}^3 $ 

## Dimension Vector Space

Let $ V $ be a vector space. Then all bases of $ V $ have the same number of vectors.

Let $ V $ be a vector space. The dimension of $ V $, denoted $ dim V $, is the number of vectors in any basis of $ V $. The dimension of the trivial vector space $ V = {0} $ is
defined to be zero.

Let $ B = \{\textbf{v}_1, \cdots , \textbf{v}_n\} $ be vectors in $ \mathbb{R}^n $. If $ \textbf{B} $ is linearly independent then $ \textbf{B} $ is a basis for $ \mathbb{R}^n $. 
Or if $ span\{\textbf{v}_1, \textbf{v}_2, \cdots, \textbf{v}_n\} = \mathbb{R}^n $ then $ \textbf{B} $ is a basis for $ \mathbb{R}^n $.

## Coordinates in an Orthonormal Basis

Let $ \textbf{B} = \{\textbf{u}_1, \textbf{u}_2, \cdots, \textbf{u}_n \} $ be an orthonormal basis for $ \mathbb{R}^n $. The coordinate vector of $ \textbf{x} $ in the basis $ \textbf{B} $ is

  $
  \textbf{x}_B =
  \begin{bmatrix}
    \textbf{u}_1 \cdot \textbf{x} \\
    \textbf{u}_2 \cdot \textbf{x} \\
    \vdots \\
    \textbf{u}_n \cdot \textbf{x}
  \end{bmatrix}
  $

## Linear Maps On Vector Spaces

Let $ T : V → U $ be a mapping of vector spaces. Then $ T $ is called a linear mapping if

- for any $ \textbf{u} $, $ \textbf{v} $ in $ V $ it holds that $ T(\textbf{u} + \textbf{v}) = T(\textbf{u}) + T(\textbf{v}) $, and

- for any scalar α and $ \textbf{u} $ in V it holds that $ T(α\textbf{v}) = αT(\textbf{v}) $.

Let $ T : V → U $ be a linear mapping.

- The kernel of $ T $ is the set of vectors $ \textbf{v} $ in the domain $ V $ that get mapped to the zero vector, that is, $ T(\textbf{v}) = 0 $. We denote the kernel of $ T $ by 
$ ker(T): ker(T) = {\textbf{v} ∈ V \ | \ T(\textbf{v}) = 0} $.

- The range of $ T $ is the set of vectors $ b $ in the co-domain $ U $ for which there exists at least one $ \textbf{v} $ in $ V $ such that $ T(\textbf{v}) = \textbf{b} $. We denote the range of $ T $ by 

  $ Range(T): Range(T) = {b ∈ U | \text{ there exists some } v ∈ U \text{ such that } T(v) = b} $.


Let $ T : V → U $ be a linear mapping. Then $ ker(T) $ is a subspace of $ V $ and $ Range(T) $ is a subspace of $ U $.