## Row Echelon Form

A matrix is in row echelon form if the following conditions are true

- The row echelon form of a matrix is not unique, a matrix can have many row echelon forms.

- All the entries beneath a leading 1 on a row is 0.

- If a row does not consist entirely of zeros, then the first nonzero number in the row is 1.

- All zero rows are the bottom of the matrix

- In any two successive rows that do not consist entirely of zeros, the leading 1 in the lower row occurs farther to the right than the leading 1 in the higher row

  $
  \begin{bmatrix}
  \color{orange}1 & 4 \\
  \color{red}0 & \color{orange}1 
  \end{bmatrix}
  \ \ \ \ \
  $
  $
  \begin{bmatrix}
  \color{orange}1 & 5 & 2\\
  \color{red}0 & \color{orange}1 & 4\\
  \color{red}0 & \color{red}0 & \color{red}0
  \end{bmatrix}
  \ \ \ \ \
  $
  $
  \begin{bmatrix}
  \color{orange}1 & 3 & 2\\
  \color{red}0 & \color{orange}1 & 7\\
  \color{red}0 & \color{red}0 & \color{orange}1
  \end{bmatrix}
  \ \ \ \ \
  $
  $
  \begin{bmatrix}
  \color{orange}1 & 3 & 2 & 4 & 7\\
  \color{red}0 & \color{orange}1 & 7 & 5 & 2\\
  \color{red}0 & \color{red}0 & \color{orange}1 & 7 & 5\\
  \color{red}0 & \color{red}0 & \color{red}0 & \color{red}0 & \color{red}0
  \end{bmatrix}
  $

### Gaussian Elimination

Row operations to convert a matrix into row echelon form is called Gaussian elimination. 

The three types of elementary row operations are:

- **Multiply a row by a nonzero number**

- **Interchange two rows**

- **Add a multiple of a row to another row**

Process:-

1- Locate the leftmost column that does not consist entirely of zeros.

2- Interchange the top row with another, if necessary, to bring a nonzero entry to the top of the column found in step 1.

3- If the entry that is now at the top of the column found in step 1 is a, multiply multiply the first row by 1/a in order to introduce a leading 1.

4- Add suitable multiples of the top row to the rows below so that all entries below the leading 1 becomes zeros.

5- Now cover the top row in the matrix and begin again with step 1 applied to the submatrix that remains. Continue int this way until the entire matrix is in row echelon form.

### Example
Use Gaussian elimination to convert this matrix to REF

$
\begin{bmatrix}
2 & 4 & 6 \\
2 & 4 & 2 \\
1 & 3 & 1
\end{bmatrix}
$

To obtain a leading 1 on $ R_1 $, divide $ R_1 $ by 2

$
\begin{bmatrix}
1 & 2 & 3 \\
2 & 4 & 2 \\
1 & 3 & 1
\end{bmatrix}
$

Set the leading element in $ R_2 $ to 1 by dividing it by 2

$
\begin{bmatrix}
1 & 2 & 3 \\
1 & 2 & 1 \\
1 & 3 & 1
\end{bmatrix}
$

Now we can create a leading 0 on $ R_2 $ by subtracting $ R_1 $ from $ R_2 $

$
\begin{bmatrix}
1 & 2 & 3 \\
0 & 0 & -2 \\
1 & 3 & 1
\end{bmatrix}
$

Two leading 0's is a good fit for $ R_3 $, so swap $ R_2 $ with $ R_3 $

$
\begin{bmatrix}
1 & 2 & 3 \\
1 & 3 & 1 \\
0 & 0 & -2
\end{bmatrix}
$

Divide $ R_3 $ by -2

$
\begin{bmatrix}
1 & 2 & 3 \\
1 & 3 & 1 \\
0 & 0 & 1
\end{bmatrix}
$

Finally, To get a leading 0 on $ R_2 $, subtract $ R_1 $ from it

$
\begin{bmatrix}
1 & 2 & 3 \\
0 & 1 & -2 \\
0 & 0 & 1
\end{bmatrix}
$

### REF using Sympy

In [1]:
import numpy as np
from sympy import Matrix

A = np.array([[2, 4, 6], [2, 4, 2], [1, 3, 1]]);

# Convert to sympy matrix
A_Mat = Matrix(A)

# Get REF (Row Echelon Form)
REF = A_Mat.echelon_form()

print(np.array(REF), '\n')

[[2 4 6]
 [0 2 -4]
 [0 0 -8]] 



## Reduced Row Echelon Form

- Similar to Row Echelon form, with the extra codition that each column with a leading 1 must have 0's above it

- Matrices must only have one reduced row echelon form; the reduced row echelon form is unique.

- Every matrix can be transformed into a reduced row echelon form by a process called Gauss-Jordan elimination

- If a square matrix $ \textbf{A} $ has linearly independent colums, then the reduced row echelon form of the matrix is the identity matrix $ \textbf{I} $

  $
  \begin{bmatrix}
  \color{orange}1 & \color{red}0 \\
  \color{red}0 & \color{orange}1 
  \end{bmatrix}
  \ \ \ \ \ \
  $
  $
  \begin{bmatrix}
  \color{orange}1 & \color{red}0 & 2 \\
  \color{red}0 & \color{orange}1 & 4 \\
  \color{red}0 & \color{red}0 & \color{red}0
  \end{bmatrix}
  \ \ \ \ \ \
  $
  $
  \begin{bmatrix}
  \color{orange}1 & \color{red}0 & 0 \\
  \color{red}0 & \color{orange}1 & \color{red}0 \\
  0 & \color{red}0 & \color{orange}1
  \end{bmatrix}
  \ \ \ \ \ \
  $
  $
  \begin{bmatrix}
  0 & \color{orange}1 & 5 & \color{red}0 & 0 & 0 & 3 & 9 & 0 & 7 \\
  0 & \color{red}0 & 0 & \color{orange}1 & \color{red}0 & 0 & 5 & 7 & 0 & 5 \\
  0 & 0 & 0 & \color{red}0 & \color{orange}1 & \color{red}0 & 7 & 3 & 0 & 3 \\
  0 & 0 & 0 & 0 & \color{red}0 & \color{orange}1 & 2 & 6 & \color{red}0 & 9 \\
  0 & 0 & 0 & 0 & 0 & \color{red}0 & 0 & 0 & \color{orange}1 & 2
  \end{bmatrix}
  $

### Gauss-Jordan Elimination

Gauss-Jordan Elimination is used to convert any matrix to reduced row echelon form.

It uses the same three elementary operations as Gaussian elimination.

It also follows a similar recipe as Gaussian elimination, but with an added extra step 6 below,

  1- Locate the leftmost column that does not consist entirely of zeros.

  2- Interchange the top row with another, if necessary, to bring a nonzero entry to the top of the column found in step 1.

  3- If the entry that is now at the top of the column found in step 1 is a, multiply multiply the first row by 1/a in order to introduce a leading 1.

  4- Add suitable multiples of the top row to the rows below so that all entries below the leading 1 becomes zeros.

  5- Now cover the top row in the matrix and begin again with step 1 applied to the submatrix that remains. Continue int this way until the entire matrix is in row echelon form.

  6- Beginnign with the last nonzero row and working upward, add suitable multiples of each row to the rows above to introduce zeros above the leading 1's.

### Example

Rewrite this following matrix in RREF

$
\begin{bmatrix}
2 & -2 & 4 \\
6 & -2 & 3 \\
3 & -2 & 4
\end{bmatrix}
$

We need a leading 1 on $ R_1 $, divide $ R_1 $ by 2

$
\begin{bmatrix}
1 & -1 & 2 \\
6 & -2 & 3 \\
3 & -2 & 4
\end{bmatrix}
$

Create a leading 0 on $ R_3 $ by subtracting $ 3 \times R_1 $ from $ R_3 $

$
\begin{bmatrix}
1 & -1 & 2 \\
6 & -2 & 3 \\
0 & 1 & -2
\end{bmatrix}
$

Create a leading 0 on $ R_2 $ by subtracting $ 6 \times R_1 $ from $ R_2 $

$
\begin{bmatrix}
1 & -1 & 2 \\
0 & 4 & -9 \\
0 & 1 & -2
\end{bmatrix}
$

We need a 0 above the leading number on $ R_2 $, add $ R_3 $ to $ R_1 $

$
\begin{bmatrix}
1 & 0 & 0 \\
0 & 4 & -9 \\
0 & 1 & -2
\end{bmatrix}
$

We need a leading 0 on $ R_3 $, apply $ -4 \times R_3 + R_2 $ 

$
\begin{bmatrix}
1 & 0 & 0 \\
0 & 4 & -9 \\
0 & 0 & -1
\end{bmatrix}
$

We need a leading 1 on $ R_3 $, multiple by -1

$
\begin{bmatrix}
1 & 0 & 0 \\
0 & 4 & -9 \\
0 & 0 & 1
\end{bmatrix}
$

We need a 0 above the leading 1 of $ R_3 $, therefore add $ 9 \times R_3 $ to $ R_2 $

$
\begin{bmatrix}
1 & 0 & 0 \\
0 & 4 & 0 \\
0 & 0 & 1
\end{bmatrix}
$

All that remains is to divide $ R_2 $  by 4

$
\begin{bmatrix}
1 & 0 & 0 \\
0 & 1 & 0 \\
0 & 0 & 1
\end{bmatrix}
$

### RREF with Sympy

In [2]:
import numpy as np
from sympy import Matrix

A = np.array([[2, -2, 4], [6, -2, 3], [3, -2, 4]]);

# Convert to sympy matrix
Mat = Matrix(A)

# Get RREF (Reduced Row Echelon Form)
RREF = Mat.rref()[0]

print(np.array(RREF))

[[1 0 0]
 [0 1 0]
 [0 0 1]]


## Pivot

- The positions of the leading 1's in a row echelon or reduced row echelon form matrix are the pivot positions.

- A nonzero entry in a pivot position is a pivot.

  $
  \begin{bmatrix}
  \color{orange}1 & -3 & 4 & 7\\
  0 & \color{orange}1 & 2 & 2\\
  0 & 0 & \color{orange}8 & 5
  \end{bmatrix}
  $

  1, 1 and 8 in the diagonals are the pivot points of the matrix.

- The columns containing the leading 1's in a row echelon or reduced row echelon form matrix are the pivot columns of the matrix.
   
- The rows containing the leading 1's are the pivot rows.

### Inverse Matrix using RREF

Also known as the 'inversion algorithm'. Let $ A $ be an $ n \times n $ square matrix. Then the matrix $ \textbf{A} $ is invertible only if its reduced row echelon form is the identity matrix $ \textbf{I} $.

Proof:

By definition $ \textbf{A}^{-1}\textbf{A} = I $

Let $ E_1, \ E_2, \ E_3, \ ..., \ E_n $ be the set of Gaussian-Jordan transformations that converts $ \textbf{A} $ to an identity matrix $ \textbf{I} $

$ \implies E_1 \ E_2 \ E_3 \ ... \ E_n \ \textbf{A} = \textbf{I} $

multiply both sides by $ \textbf{A}^{-1} $

$ \implies E_1 \ E_2 \ E_3 \ ... \ E_n \ \textbf{A} \textbf{A}^{-1} = \textbf{I} \textbf{A}^{-1} $

$ \implies E_1 \ E_2 \ E_3 \ ... \ E_n \ \textbf{I} = \textbf{A}^{-1} $

$ \therefore \textbf{A}^{-1} = E_1 \ E_2 \ E_3 \ ... \ E_n $

### Example
Find the inverse of the following matrix by transforming it to reduce row echelon form

$
\begin{bmatrix}
1 & 2 & 3 \\
2 & 5 & 3 \\
1 & 0 & 8
\end{bmatrix}
$

Start by augmenting the matrix with the identity matrix


$
\begin{bmatrix}
1 & 2 & 3 & | & 1 & 0 & 0 \\
2 & 5 & 3 & | & 0 & 1 & 0 \\
1 & 0 & 8 & | & 0 & 0 & 1 
\end{bmatrix}
$

Apply Gauss-Jordan transformations such that the left hand of the matrix becomes the identity matrix

- $ R_2 : R_2 - 2 R_1 $
- $ R_3 : R_3 - R_1 $

  $
  \begin{bmatrix}
  1 & 2 & 3 & | & 1 & 0 & 0 \\
  0 & 1 & -3 & | & -2 & 1 & 0 \\
  0 & -2 & 5 & | & -1 & 0 & 1 
  \end{bmatrix}
  $

- $ R_1 : R_1 - 2 R_2 $
- $ R_3 : R_3 + 2 R_2 $

  $
  \begin{bmatrix}
  1 & 0 & 9 & | & 5 & -2 & 0 \\
  0 & 1 & -3 & | & -2 & 1 & 0 \\
  0 & 0 & -1 & | & -5 & 2 & 1 
  \end{bmatrix}
  $

- $ R_1 : R_1 + 9 R_3 $
- $ R_2 : R_2 - 3 R_3 $
- $ R_3 : - 1 R_3 $

  $
  \begin{bmatrix}
  1 & 0 & 0 & | & -40 & 16 & 9 \\
  0 & 1 & 0 & | & 13 & -5 & -3 \\
  0 & 0 & 1 & | & 5 & -2 & -1 
  \end{bmatrix}
  $

$ \therefore $ the inverse matrix is 

  $
  \begin{bmatrix}
  -40 & 16 & 9 \\
  13 & -5 & -3 \\
  5 & -2 & -1 
  \end{bmatrix}
  $

In [18]:
# let's check the invese using SciPy
A = np.array([[1, 2, 3], [2, 5, 3], [1, 0, 8]]);

# Convert to sympy matrix
A_Mat = Matrix(A)

# Get RREF (Reduced Row Echelon Form)
RREF = A_Mat.rref()[0]

print(np.array(RREF), '\n')

print(sp.linalg.inv(A))

[[1 0 0]
 [0 1 0]
 [0 0 1]] 

[[-40.  16.   9.]
 [ 13.  -5.  -3.]
 [  5.  -2.  -1.]]
