## Linear Independence

- The set of vectors $ \{\textbf{v}_1, \textbf{v}_2, ... , \textbf{v}_n\} $ is linearly independent if and only if $ \textbf{0} $ can be written in only one way as a linear combination of $ \{\textbf{v}_1, \textbf{v}_2, ..., \textbf{v}_n\} $. In other words, if 
  
  $ t_1\textbf{v}_1 + t_2 \textbf{v}_2 + ···+ t_n \textbf{v}_n = \textbf{0} $ 
  
  then necessarily the coefficients $ t_1, t_2, ..., t_n $ are all zero.
  
- A set of vectors $ \{\textbf{v}_1, \textbf{v}_2, ..., \textbf{v}_n\} $ is said to be linearly dependent if some $ \textbf{v}_j $ can be written as a linear combination of the other vectors, that is, if $ \textbf{v}_j \in span\{ \textbf{v}_1, ..., \textbf{v}_{j−1}, \textbf{v}_{j+1}, ..., \textbf{v}_n \} $. 

  If $ \textbf{v}_1, \textbf{v}_2, ..., \textbf{v}_n $ is not linearly dependent then we say that $ \textbf{v}_1, \textbf{v}_2, ..., \textbf{v}_n $ is linearly independent.

- The set $ \{\textbf{v}_1, \textbf{v}_2, ..., \textbf{v}_n\} $ is linearly independent if and only if the the rank of $ \textbf{A} $ is $ r = n $, that is, if the number of leading entries $ r $ in the REF (or RREF) of $ \textbf{A} $ is exactly $ n $.

### Example 1

Show the following vectors are linearly dependent 

$ 
\textbf{v}_1 =
\begin{bmatrix}
\ 1 \ \\
\ 2 \ \\
\ 3 \
\end{bmatrix}
\ \ \ \
\textbf{v}_2 =
\begin{bmatrix}
\ 4 \ \\
\ 5 \ \\
\ 6 \
\end{bmatrix}
\ \ \ \
\textbf{v}_3 =
\begin{bmatrix}
\ 2 \ \\
\ 1 \ \\
\ 0 \
\end{bmatrix}
$

Solution: 

Since a vector is linearly dependent if it can be written as a linear combination of the other vectors in the same set $ \textbf{v}_j \in span\{ \textbf{v}_1, ..., \textbf{v}_{j−1}, \textbf{v}_{j+1}, ..., \textbf{v}_n \} $. We simply need to show one of the vectors can be set as a linear combination of the other vectors.

We can visually see that

$ 
\textbf{v}_2 = 2\textbf{v}_1 + \textbf{v}_3
    = 2  
\begin{bmatrix}
\ 1 \ \\
\ 2 \ \\
\ 3 \
\end{bmatrix}
+
\begin{bmatrix}
\ 2 \ \\
\ 1 \ \\
\ 0 \
\end{bmatrix}
    =
\begin{bmatrix}
\ 4 \ \\
\ 5 \ \\
\ 6 \
\end{bmatrix}    
$

Therefore, since $ \textbf{v}_2 \in span \{ \textbf{v}_1, \textbf{v}_3 \} $ then the vectors $ \{ \textbf{v}_1, \textbf{v}_2, \textbf{v}_3 \} $ are linearly dependent

### Example 2

Verify whether the set $ \{ \textbf{u}, \textbf{v}, \textbf{w} \} $ is linearly independent.

$ 
\textbf{u} =
\begin{bmatrix}
\ 1 \ \\
\ 1 \ \\
\ 0 \
\end{bmatrix}
\ \ \ \
\textbf{v} =
\begin{bmatrix}
\ 1 \ \\
\ 0 \ \\
\ 1 \
\end{bmatrix}
\ \ \ \
\textbf{v} =
\begin{bmatrix}
\ 0 \ \\
\ 1 \ \\
\ 1 \
\end{bmatrix}
$

**Solution :**

Suppose we have a linear combination 

$ a \textbf{u} + b \textbf{v} + c \textbf{w} = \textbf{0} $

We need to show that this is only true if $ a=0 $, $ b=0 $ and $ c=0 $

We do this by forming this column matrix

$
A = 
\begin{bmatrix}
1 & 1 & 0 \\
1 & 0 & 1 \\
0 & 1 & 1 
\end{bmatrix}
$

and show that $ \textbf{Ax} = \textbf{0} $

only has the trivial solution.

In [1]:
import numpy as np
import scipy as sp


# create the matrix
A = np.array([[1, 1, 0], [1, 0, 1], [0, 1, 1]]);


# find inverse using scipy
print(sp.linalg.inv(A))

[[ 0.5  0.5 -0.5]
 [ 0.5 -0.5  0.5]
 [-0.5  0.5  0.5]]


### The maximum size of a linearly independent set

Let $ \textbf{v}_1, \textbf{v}_2, ..., \textbf{v}_p $ be a set of vectors in $ \mathbb{R}^n $. If $ p > n $ then $ \textbf{v}_1, \textbf{v}_2, ..., \textbf{v}_p $ are linearly dependent. Equivalently, if the vectors $ \textbf{v}_1, \textbf{v}_2, ..., \textbf{v}_p $ in $ \mathbb{R}^n $ are linearly independent then $ p ≤ n $.