## Matrix Row & Column Vector Spaces

- For any matrix, the rows and columns can be considered as vectors.

- If we have an $ m \times n $ matrix $ \textbf{A} $, then it will have $ m $ row vectors and $ n $ column vectors, denoted by $ \textbf{row(A)} $ and $ \textbf{col(A)} $.

- The subspace spanned by the row vectors of $ \textbf{A} $, $ row(\textbf{A}) $, is called the row space of $ \textbf{A} $

- The subspace spanned by the column vectors of $ \textbf{A} $, $ \textbf{col(A)} $, is called the column space of $ \textbf{A} $

### Example

$ 
\textbf{A} = 
\begin{bmatrix}
  0 & 1 \\
  2 & 3 \\
  -1 & 2 
\end{bmatrix}
$

Will have row vectors $ \textbf{row(A)} $

$ 
\textbf{r}_1=
\begin{bmatrix}
  0 & 1
\end{bmatrix}
, \ \ \ \
\textbf{r}_2=
\begin{bmatrix}
  2 & 3
\end{bmatrix}
, \ \ \ \
\textbf{r}_3=
\begin{bmatrix}
  -1 & 2
\end{bmatrix}
$

and column vectors $ \textbf{col(A)} $

$
\textbf{c}_1=
\begin{bmatrix}
  0 \\
  2 \\
  -1
\end{bmatrix}
, \ \ \ \
\textbf{c}_2=
\begin{bmatrix}
  1 \\
  3 \\
  2 
\end{bmatrix}
$

### Column Space

- If $ \textbf{A} $ is an m x n matrix, then the subspace of $ \mathbb{R} $ spanned by the column vectors of $ \textbf{A} $ is denoted $ \textbf{col({A})} $ and called the column space of $ \textbf{A} $. 

  $ 
  \textbf{A} = 
    \begin{bmatrix}
    a_{11} & a_{12} & \cdots & a_{1n} \\
    a_{21} & a_{22} & \cdots & a_{2n} \\
    \vdots & \vdots &   & \vdots \\
    a_{m1} & a_{m2} & \cdots & a_{mn}
    \end{bmatrix}
  $

  with column vectors

  $ 
  \textbf{c}_1=
  \begin{bmatrix}
    a_{11} \\
    a_{21} \\
    \vdots \\
    a_{m1}
  \end{bmatrix}
  , \ \ \ \
  \textbf{c}_2=
  \begin{bmatrix}
    a_{12} \\
    a_{22} \\
    \vdots \\
    a_{m2}
  \end{bmatrix}
  , \ \ \ \
  \cdots
  , \ \ \ \
  \textbf{c}_n=
  \begin{bmatrix}
    a_{1n} \\
    a_{2n} \\
    \vdots \\
    a_{mn}
  \end{bmatrix}
  $

  A vector that belongs to the space $ \textbf{col(A)} $ is a linear combination of the column vectors $ \{ \textbf{c}_1, \ \textbf{c}_2, \ ..., \ \textbf{c}_n \} $.

  $ \therefore \textbf{x} = x_1 \ \textbf{c}_1 + x_2 \ \textbf{c}_2 + ... + x_n \ \textbf{c}_n$

  We therefore have:

  - If $ \textbf{x}, \textbf{y} \in \textbf{col(A)}$, then  $ \textbf{x} + \textbf{y} \in \textbf{col(A)} $
  - If $ \textbf{x} \in \textbf{col(A)}$ and $ k $ is a scalar, then  $ k \textbf{x} \in \textbf{col(A)} $

- If a matrix $ \textbf{R} $ is in row echelon form, then the column vectors with the leading 1's of the row vectors form a basis for $ col(\textbf{R}) $

## Basis Vectors for the Row Space

Basis vectors are a set of linearly independent vectors that span a space. In the case of matrices, they will have both row basis vectors, as well column basis vectors.

To evaluate the basis vectors for the matrix row space, $ \textbf{row(A)} $, we need to transform the matrix to row echelon form. The nonzero rows of the matrix will form a basis for $ \textbf{row(A)} $.

#### Example

Evaluate the basis vectors for the row space of the following matrix

$ 
\textbf{A} = 
  \begin{bmatrix}
  1 & -3 & 4 & -2 & 5 & 4 \\
  2 & -6 & 9 & -1 & 8 & 2 \\
  2 & -6 & 9 & -1 & 9 & 7 \\
  -1 & 3 & -4 & 2 & -5 & -4 \\
  \end{bmatrix}
$

Start by evaluating the row echelon form of this matrix

In [20]:
A = np.array([[1, -3, 4, -2, 5, 4], 
              [2, -6, 9, -1, 8, 2], 
              [2, -6, 9, -1, 9, 7], 
              [-1, 3, -4, 2, -5, -4]])

# Convert to sympy matrix
A_Mat = Matrix(A)

# Get RREF (Reduced Row Echelon Form)
REF = A_Mat.echelon_form()

print(np.array(REF))

[[1 -3 4 -2 5 4]
 [0 0 1 3 -2 -6]
 [0 0 0 0 1 5]
 [0 0 0 0 0 0]]


Therefore the basis vectors for $ \textbf{row(A)} $ are

$ 
\textbf{r}_{1}=
\begin{bmatrix}
  1 & -3 & 4 & -2 & 5 & 4
\end{bmatrix}
$

$
\textbf{r}_{2}=
\begin{bmatrix}
  0 & 0 & 1 & 3 & -2 & -6
\end{bmatrix}
$

$
\textbf{r}_{3}=
\begin{bmatrix}
  0 & 0 & 0 & 0 & 1 & 5
\end{bmatrix}
$

These are three linearly independent vectors that span the row space of the matrix.

## Basis Vectors for the Column Space

We can find the basis vectors for the column space of a matrix, $ \textbf{col(A)} $, as follows

1. Reduce the the matrix to row echelon form
   
2. Identify the columns containing the leading 1's
   
3. The corresponding columns of the original matrix form a basis for $ \textbf{col(A)} $

#### Example:

Evaluate the basis vectors for the column space of the following matrix

$ 
\textbf{A} = 
  \begin{bmatrix}
  1 & -3 & 4 & -2 & 5 & 4 \\
  2 & -6 & 9 & -1 & 8 & 2 \\
  2 & -6 & 9 & -1 & 9 & 7 \\
  -1 & 3 & -4 & 2 & -5 & -4 \\
  \end{bmatrix}
$

Find the row echelon form of the matrix

In [21]:
A = np.array([[1, -3, 4, -2, 5, 4], 
              [2, -6, 9, -1, 8, 2], 
              [2, -6, 9, -1, 9, 7], 
              [-1, 3, -4, 2, -5, -4]])

# Convert to sympy matrix
A_Mat = Matrix(A)

# Get RREF (Reduced Row Echelon Form)
REF = A_Mat.echelon_form()

print(np.array(REF))

[[1 -3 4 -2 5 4]
 [0 0 1 3 -2 -6]
 [0 0 0 0 1 5]
 [0 0 0 0 0 0]]


Find the columns that have a leading 1, they will be columns 1, 3 and 5

$ 
\textbf{c}_1=
\begin{bmatrix}
  1 \\
  0 \\
  0 \\
  0
\end{bmatrix}
, \ \ \ \
\textbf{c}_3=
\begin{bmatrix}
  4 \\
  1 \\
  0 \\
  0
\end{bmatrix}
, \ \ \ \
\textbf{c}_5=
\begin{bmatrix}
  5 \\
  -2 \\
  1 \\
  0
\end{bmatrix}
$

The basis vectors of the matrix columns space will be the columns 1, 3 and 5 in the original matrix

Therefore the column space, $ \textbf{col(A)} $, basis vectors will be

$ 
\textbf{c}_1=
\begin{bmatrix}
  1 \\
  2 \\
  3 \\
  -1
\end{bmatrix}
, \ \ \ \
\textbf{c}_3=
\begin{bmatrix}
  4 \\
  9 \\
  9 \\
  -4
\end{bmatrix}
, \ \ \ \
\textbf{c}_5=
\begin{bmatrix}
  5 \\
  8 \\
  9 \\
  -5
\end{bmatrix}
$

These basis vectors are linearly independent and form basis vectors for $ \textbf{col(A)} $