## Eigenvectors and Eigenvalues

- Let $ \textbf{A} $ be an $ n \times n $ matrix and let $ \textbf{v} $ be a non-zero vector. If the equation $ \textbf{Av} = \lambda \textbf{v} $ is true for some scalar $ \lambda $, then we call the vector $ \textbf{v} $ an eigenvector of $ \textbf{A} $ and we call the scalar $ \lambda $ an eigenvalue of $ \textbf{A} $.

- Let $ \textbf{A} $ be an $ n \times n $ matrix. The polynomial $ p(\lambda) = |\textbf{A} − \lambda \textbf{I}| $ is called the characteristic polynomial and is of $ n^{th} $ degree.

- If $ \textbf{A} $ is an $ n \times n $ matrix that has n distinct eigenvalues $ \{\lambda_1, \lambda_2, . . . , \lambda_n \} $ with corresponding eigenvectors $ \lambda_{i} $. Then $ \{\textbf{v}_1, \textbf{v}_2, \cdots, \textbf{v}_n\} $, then the eigenvectors forms a basis for $ \mathbb{R}^n $.

- The square matrix $ \textbf{A} $ is invertible if and only if $ \lambda = 0 $ is not an eigenvalue of $ \textbf{A} $.

- Let $ \textbf{A} $ be a triangular matrix (either upper or lower). Then the eigenvalues of $ \textbf{A} $ are its diagonal entries

- If $ \textbf{A} $ is a symmetric matrix then all of its eigenvalues are real numbers

- Let $ \textbf{A} $ be a symmetric matrix. If $ \textbf{v}_1 $ and $ \textbf{v}_2 $ are eigenvectors of $ \textbf{A} $ corresponding to distinct eigenvalues then $ \textbf{v}_1 $ and $ \textbf{v}_2 $ are orthogonal, that is, $ \textbf{v}_1 . \textbf{v}_2 = 0 $

#### Example using SciPy

In [1]:
import numpy as np
import scipy as sp

A = np.array([[2, 2, 4], [1, 3, 5], [2, 3, 4]])

w, v= sp.linalg.eig(A)

print('List of Eigenvalues', w)
print('\nList of Eigenvectors\n', v)

List of Eigenvalues [ 8.80916362+0.j  0.92620912+0.j -0.73537273+0.j]

List of Eigenvectors
 [[-0.52799324 -0.77557092 -0.36272811]
 [-0.604391    0.62277013 -0.7103262 ]
 [-0.59660259 -0.10318482  0.60321224]]


In [2]:
# proof

eval_1 = 8.80916362
eval_2 = 0.92620912
eval_3 = -0.73537273

evec_1 = np.array([-0.52799324, -0.604391, -0.59660259])

print(A @ evec_1)
print(eval_1 * evec_1)

[-4.65117884 -5.32417919 -5.25556984]
[-4.65117884 -5.32417921 -5.25556983]
