## Cholesky Decomposition

Cholesky decomposition is a special case of $ \textbf{LU} $ decomposition applicable to Hermitian positive definite matrices.

When $ \textbf{A} = \textbf{A}^H $ and $ \textbf{x}^H \textbf{Ax} \ge 0 $ for all x, then decompositions of $ \textbf{A} $ can be found so that

$ \textbf{A} = \textbf{U}^{H}\textbf{U} $

$ \textbf{A} = \textbf{LL}^{H} $

where $ \textbf{L} $ is lower triangular and $ \textbf{U} $ is upper triangular where $ \textbf{L} = \textbf{U}^{H} $

The Cholesky decomposition is often used as a fast way of solving $ \textbf{Ax = b} $ (when $ \textbf{A} $ is both Hermitian/symmetric and positive-definite).

In [25]:
A = np.array([[6, 3, 4, 8], [3, 6, 5, 1], [4, 5, 10, 7], [8, 1, 7, 25]])

L = sp.linalg.cholesky(A, lower = True)
U = sp.linalg.cholesky(A, lower = False)

print(A, '\n')

print(L, '\n')

print(U, '\n')

print(L @ U)

[[ 6  3  4  8]
 [ 3  6  5  1]
 [ 4  5 10  7]
 [ 8  1  7 25]] 

[[ 2.44948974  0.          0.          0.        ]
 [ 1.22474487  2.12132034  0.          0.        ]
 [ 1.63299316  1.41421356  2.30940108  0.        ]
 [ 3.26598632 -1.41421356  1.58771324  3.13249102]] 

[[ 2.44948974  1.22474487  1.63299316  3.26598632]
 [ 0.          2.12132034  1.41421356 -1.41421356]
 [ 0.          0.          2.30940108  1.58771324]
 [ 0.          0.          0.          3.13249102]] 

[[ 6.  3.  4.  8.]
 [ 3.  6.  5.  1.]
 [ 4.  5. 10.  7.]
 [ 8.  1.  7. 25.]]
