## QR Decomposition

QR decomposition of a matrix $ \textbf{A} $ is a decomposition into a product $ \textbf{A = QR} $ of an orthonormal matrix $ \textbf{Q} $ and an upper triangular matrix $ \textbf{R} $ .

In [26]:
A = np.array([[12, -51, 4], [6, 167, -68], [-4, 24, -41]])
Q, R = sp.linalg.qr(A)

print(A, '\n')

print(Q, '\n')

print(R, '\n')

print(Q @ R)

[[ 12 -51   4]
 [  6 167 -68]
 [ -4  24 -41]] 

[[-0.85714286  0.39428571  0.33142857]
 [-0.42857143 -0.90285714 -0.03428571]
 [ 0.28571429 -0.17142857  0.94285714]] 

[[ -14.  -21.   14.]
 [   0. -175.   70.]
 [   0.    0.  -35.]] 

[[ 12. -51.   4.]
 [  6. 167. -68.]
 [ -4.  24. -41.]]
