## Rank Theorem

- The rank of a matrix $ \textbf{A} $ is the dimension of its column space. We will use $ rank(\textbf{A}) $ to denote the rank of $ \textbf{A} $

- The nullity of a matrix $ \textbf{A} $ is the dimension of its null space $ Null(A) $. We will use $ nullity(\textbf{A}) $ to denote the nullity of $ \textbf{A} $.

- (Rank Theorem) Let $ \textbf{A} $ be a $ m \times n $ matrix. The rank of $ \textbf{A} $ is the number of leading 1's in its RREF. Moreover, the following equation holds:

  $ n = rank(\textbf{A}) + nullity(\textbf{A}) $

- Let $ \textbf{A} $ be a $ n \times n $ matrix. The following statements are equivalent:
  
  - The columns of $ \textbf{A} $ form a basis for $ \mathbb{R}^n $
    
  - $ Col(\textbf{A}) = \mathbb{R}^n $
    
  - $ rank(\textbf{A}) = n $
    
  - $ Null(\textbf{A}) = {0} $
    
  - $ nullity(\textbf{A}) = 0 $
    
  - $ A $ is an invertible matrix

## Rank of Matrix

The rank of a matrix is the number of linearly independent rows, or equivalently, the number of linearly independent columns.

- The rank of a matrix is always positive, except for a zero matrix which has a rank of zero.

- The rank of a matrix can be found using three methods. The most easiest of these methods is "converting matrix into echelon form".

  - Using row echelon form
  - Using normal form
  - Minor method

### Rank of Matrix using row echelon form

The rank of the matrix will be equal to the number of linearly independent rows of the row echelon form of this matrix.

#### Example 1

Calculate the rank of the following matrix

$
\begin{bmatrix}
2 & -1 & 0 \\
1 & 2 & 1 \\
1 & 3 & 1
\end{bmatrix}
$



In [1]:
import numpy as np
from sympy import Matrix

A = np.array([[2, -1, 0], [1, 2, 1], [1, 3, 1]]);

# Convert to sympy matrix
A_Mat = Matrix(A)

# Get REF (Row Echelon Form)
REF = A_Mat.echelon_form()

print(np.array(REF), '\n')

[[2 -1 0]
 [0 5 2]
 [0 0 -4]] 



$
\begin{bmatrix}
2 & -1 & 0 \\
0 & 5 & 2 \\
0 & 0 & -4
\end{bmatrix}
$

The resulting row echelon matrix has 3 non-zero rows (and columns), this means the rank of this matrix is 3.

#### Example 2

Calculate the rank of this matrix

$
\begin{bmatrix}
1 & 2 & 1 \\
-2 & -3 & 1 \\
3 & 5 & 0 \\
2 & 4 & 2
\end{bmatrix}
$



In [2]:
import numpy as np
from sympy import Matrix

A = np.array([[1, 2, 1], [-2, -3, 1], [3, 5, 0], [2, 4, 2]]);

# Convert to sympy matrix
A_Mat = Matrix(A)

# Get REF (Row Echelon Form)
REF = A_Mat.echelon_form()

print(np.array(REF), '\n')

[[1 2 1]
 [0 1 3]
 [0 0 0]
 [0 0 0]] 



$
\begin{bmatrix}
1 & 2 & 1 \\
0 & 1 & 3 \\
0 & 0 & 0 \\
0 & 0 & 0
\end{bmatrix}
$

There are 2 independent rows non-zero rows, therefore the rank of the matrix is 2.

#### Example 3

Evaluate the rank of the following matrix

$
\begin{bmatrix}
1 & 2 & 3 \\
2 & 3 & 5 \\
3 & 4 & 7 \\
4 & 5 & 9
\end{bmatrix}
$

We can see that column 1 and 2 are linearly independent. However, column 3 is the sum of both 1 and 2. Therefore since there are only two linearly independent columns, the rank of the matrix is 2.