## Linear Systems

Linear systems are represented using linear equations, where $ x_i $ are the unknowns we need to evaluate, $ a_{ij} $ and $ b_i $ are known

$ a_{11} \ x_{1} + a_{12} \ x_{2} + \cdot\cdot\cdot + a_{1n} \ x_{n} = b_1 $

$ a_{21} \ x_{1} + a_{22} \ x_{2} + \cdot\cdot\cdot + a_{2n} \ x_{n} = b_2 $

$ \ \ \ \ \vdots \ \ \ \ \ \ \ \ \ \ \ \ \vdots $ 

$ a_{m1} \ x_{1} + a_{m2} \ x_{2} + \cdot\cdot\cdot + a_{mn} \ x_{n} = b_3 $

These equations can be represented in matrix form as $ \textbf{Ax=b} $

$ 
\begin{bmatrix}
a_{11} & a_{12} & \cdots & a_{1n} \\
a_{21} & a_{22} & \cdots & a_{2n} \\
\vdots & \vdots & \ddots & \vdots \\
a_{m1} & a_{m2} & \cdots & a_{mn}
\end{bmatrix}
\begin{bmatrix}
x_{1} \\
x_{2} \\
\vdots \\
x_{n}
\end{bmatrix}
    =
\begin{bmatrix}
b_{1} \\
b_{2} \\
\vdots \\
b_{n}
\end{bmatrix}
$

To solve these equations, convert the matrix equation to an augmented matrix as follows

$ 
\begin{bmatrix}
a_{11} & a_{12} & \cdots & a_{1n} & | & b_1 \\
a_{21} & a_{22} & \cdots & a_{2n} & | & b_2 \\
\vdots & \vdots & \ddots & \vdots & | & \vdots \\
a_{m1} & a_{m2} & \cdots & a_{mn} & | & b_m
\end{bmatrix}
$

Then transform to RREF

## Solution Rules 

Solutions to linear systems can have several forms:

- One solution (consistent and independent)
  
  RREF is the identity matrix.
  
  $ 
  \begin{bmatrix}
  1 & 0 & 0 & | & b_1 \\
  0 & 1 & 0 & | & b_2 \\
  0 & 0 & 1 & | & b_3
  \end{bmatrix}
  $
  
- Many solutions (consistent and dependent)
  
  RREF has less non-zero rows than there are variables.

  $ 
  \begin{bmatrix}
  1 & 0 & 0 & | & b_1 \\
  0 & 1 & 0 & | & b_2 \\
  0 & 0 & 0 & | & 0
  \end{bmatrix}
  $
  
  
- No solutions (Inconsistent and independent)

  RREF has less non-zero rows than there are variables, with a value on the right of the augmentation line

  $ 
  \begin{bmatrix}
  1 & 0 & 0 & | & b_1 \\
  0 & 1 & 0 & | & b_2 \\
  0 & 0 & 0 & | & b_3
  \end{bmatrix}
  $

### One Solution

- For two equations with two unknowns, each representing a line, the lines cross at one point Therefore the solution is consistent and independent 
  
  The example below shows two lines that cross at the point (5, 2)

  $ 3x + y = 17 $

  $ 4x - y = 18 $

  <img src="./images/two_equations_one_solution.png" width="350px">
  
  Solve this using RREF

  $ 
  \begin{bmatrix}
  3 & 1 & | & 17 \\
  4 & -1 & | & 18 
  \end{bmatrix}
  $

In [1]:
import numpy as np
from sympy import Matrix

A = np.array([[3, 1, 17], [4, -1, 18]]);

# Convert to sympy matrix
Mat = Matrix(A)

# Get RREF (Reduced Row Echelon Form)
RREF = Mat.rref()[0]

print(np.array(RREF))

[[1 0 5]
 [0 1 2]]


$ 
\begin{bmatrix}
1 & 0 & | & 5 \\
0 & 1 & | & 2 
\end{bmatrix}
$

This is a consistent RREF

$ \implies x=5, \ \ \ y=2 $

- For Three equations with three unknowns, the three planes meet at a single point and produce only one solution. Therefore the solution is consistent and independent.
  
  <img src="./images/three_equations_one_solution1.png" width="350px">

  The example below shows three planes intersecting at only a single point (3, −2, 1) 

  $ x + y + z = 2 $

  $ 6x - 4y + 5z = 31 $
  
  $ 5x + 2y + 2z = 13 $

  <img src="./images/three_equations_one_solution2.png" width="350px">

  Use RREF to evaluate

  $ 
  \begin{bmatrix}
  1 & 1 & 1 & | & 2 \\
  6 & -4 & 5 & | & 31 \\
  5 & 2 & 2 & | & 13 
  \end{bmatrix}
  $

In [2]:
import numpy as np
from sympy import Matrix

A = np.array([[1, 1, 1, 2], [6, -4, 5, 31], [5, 2, 2, 13]]);

# Convert to sympy matrix
Mat = Matrix(A)

# Get RREF (Reduced Row Echelon Form)
RREF = Mat.rref()[0]

print(np.array(RREF))

[[1 0 0 3]
 [0 1 0 -2]
 [0 0 1 1]]


$ 
\begin{bmatrix}
1 & 0 & 0 & | & 3 \\
0 & 1 & 0 & | & -2 \\
0 & 0 & 1 & | & 1 \\
\end{bmatrix}
$

This is a consistent RREF

$ \implies x=3, \ \ \ y=-2, \ \ \ z=1 $

## Multiple Solutions

- For two equations with two unknowns, this occurs when one of the equations is a multiple of the other equation. This means we only have one equation with two unknowns.
  
  Graphically, the two lines go through the same points

  $ 2x+4y = 8 $

  $ x+2y = 4 $

  Every point on the two lines is a solution, so we have an infinite number of solutions
  
  <img src="./images/two_equations_many_solutions.png" width="304px">

  Use RREF to evaluate

  $ 
  \begin{bmatrix}
  2 & 4 & | & 8 \\
  1 & 2 & | & 4
  \end{bmatrix}
  $

In [5]:
import numpy as np
from sympy import Matrix

A = np.array([[2, 4, 8], [1, 2, 4]]);

# Convert to sympy matrix
Mat = Matrix(A)

# Get RREF (Reduced Row Echelon Form)
RREF = Mat.rref()[0]

print(np.array(RREF))

[[1 2 4]
 [0 0 0]]


$ 
\begin{bmatrix}
1 & 2 & | & 4 \\
0 & 0 & | & 0
\end{bmatrix}
$

This is a consistent RREF

$ \implies x+2y=4 \ \ \implies y = \dfrac{1}{2}(4-x) \ \ \ $ provides all the infinite solutions


- For three equations with three unknowns, this occurs when the planes intersect each other on one line

  <img src="./images/three_equations_many_solutions1.png" width="350px">

  The example below shows three planes intersecting through a finite length line
  
  $ x + y + z = 7 $

  $ 3x – 2y – z = 4 $

  $ x + 6y + 5z = 24 $
  
  <img src="./images/three_equations_many_solutions2.png" width="350px">

  Let's obtain the solution using RREF

  $ 
  \begin{bmatrix}
  1 & 1 & 1 & | & 7 \\
  3 & -2 & -1 & | & 4 \\
  1 & 6 & 5 & | & 24 
  \end{bmatrix}
  $

In [6]:
import numpy as np
from sympy import Matrix

A = np.array([[1, 1, 1, 7], [3, -2, -1, 4], [1, 6, 5, 24]]);

# Convert to sympy matrix
Mat = Matrix(A)

# Get RREF (Reduced Row Echelon Form)
RREF = Mat.rref()[0]

print(np.array(RREF))

[[1 0 1/5 18/5]
 [0 1 4/5 17/5]
 [0 0 0 0]]


$ 
\begin{bmatrix}
1 & 0 & 1/5 & | & 18/5 \\
0 & 1 & 4/5 & | & 17/5 \\
0 & 0 & 0 & | & 0 
\end{bmatrix}
$

This is a consistent RREF

$ \implies x + \dfrac{1}{5} z = \dfrac{18}{5} \ \ \implies x = \dfrac{1}{5} (z-18) $  

$ \implies y + \dfrac{4}{5} z = \dfrac{17}{5} \ \ \implies y = \dfrac{1}{5} (17 - 4z) $  

The infinite solution gives the line

$ x= \dfrac{1}{5} (t-18), \ \ \ y = -\dfrac{1}{5}(4t -17), \ \ \ z = t $

## No Solution

- For two equations with two unknowns, no solution exists if the two lines are parallel.

  $ 3x+2y=5 $

  $ 6x+4y=8 $

  <img src="./images/two_equations_no_solution.png" width="310px">

  Use RREF to evaluate the solution

  $ 
  \begin{bmatrix}
  3 & 2 & | & 5 \\
  6 & 4 & | & 8
  \end{bmatrix}
  $

In [7]:
import numpy as np
from sympy import Matrix

A = np.array([[3, 2, 5], [6, 4, 8]]);

# Convert to sympy matrix
Mat = Matrix(A)

# Get RREF (Reduced Row Echelon Form)
RREF = Mat.rref()[0]

print(np.array(RREF))

[[1 2/3 0]
 [0 0 1]]


$ 
\begin{bmatrix}
1 & 2/3 & | & 0 \\
0 & 0 & | & 1
\end{bmatrix}
$

This is an inconsistent RREF, hence no solutions.

- For three equations with three unknowns, the plains never all touch at a point or a line
  
  <img src="./images/three_equations_no_solution1.png" width="650px">

### Homogenous Linear Systems

- A homogenous system can be written in matrix form as $ \textbf{Ax}= \textbf{0} $ and always has one of two possible solutions

  - A trivial solution $ \textbf{x=0} $. If the matrix $ \textbf{A} $ is invertible (i.e. $ |\textbf{A}| \neq 0 $) then this is always true.

  - Infinitely many solutions. This occurs when the set of equations has more unknowns than equations, i.e. $ n > m $

- In the 2D case, the homogenous equations either describe two lines that cross at the origin (no offset term), or two lines that are parallel and stacked on top of each other.

  For the trivial case, the lines always meet at the origin (none of the lines is offset from the origin):

  <img src="./images/homogenous_trivial.png" width="300px" style="filter:invert(1)">    

  For the infinite case (the lines are stacked on each other and parallel):

  <img src="./images/homogenous_infinite.png" width="304px" style="filter:invert(1)">

  #### Example 1:

  $ x_1 - 5 x_2 = 0 $

  $ x_1 + 2 x_2 = 0 $

  These equations represent the lines in the first image above. The lines clearly cross at the origin and therefore we expect the trivial solution $ \textbf{x} = 0 $.

  from the first equation, we have

  $ \implies x_1 = 5 x_2 $

  plug this into the second equation

  $ \implies 5 x_2 = -2 x_2 $

  The only way this can be true is if $ x_2 = 0 $ and $ x_1 = 0 $, so the solution is 
  $ \textbf{x} =
    \begin{bmatrix}
      0 \\
      0
    \end{bmatrix} 
  $

  In matrix form we have

  $ 
  \textbf{A} =
  \begin{bmatrix}
  1 & -5 \\
  1 & 2 
  \end{bmatrix}
  $

  with determinant $ |\textbf{A}| = 7 $

  Therefore these homogenous equations have the trivial solution

  #### Example 2:

  $ x_1 + 2 x_2 = 0 $

  $ 2 x_1 + 4 x_2 = 0 $

  These equations represent the lines in the second image above. The lines are both parallel and stacked on top of each other.

  from the first equation, we have

  $ \implies x_1 = -2 x_2 $

  plug this into the second equation

  $ \implies 2 (-2 x_2) = -4 x_2  \implies x_2 = x_2 $

  This is true for an infinite number of values of $ x_2 $, also infinite values of $ x_1 = -2 x_2 $

  So all these vectors are solutions for all $ t \in \mathbb{R}^1 $

  $ 
  \textbf{x} =
  \begin{bmatrix}
  -2t \\
  t 
  \end{bmatrix}
  $

  In matrix form we have

  $ 
  \textbf{A} =
  \begin{bmatrix}
  1 & 2 \\
  2 & 4 
  \end{bmatrix}
  $

  with determinant $ |\textbf{A}| = 0 $

  Let's check our result with $ x_2 = 5 $ and $ x_1 = -10 $

  $ 
  \begin{bmatrix}
  1 & 2 \\
  2 & 4 
  \end{bmatrix}
  \begin{bmatrix}
  -10 \\
  5  
  \end{bmatrix}
      =
  \begin{bmatrix}
  0 \\
  0  
  \end{bmatrix}
  $

  Therefore these homogenous equations have infinitely many solutions.

## Non-Homogenous Linear Systems

- A system of linear equations $ \textbf{Ax=b} $ is consistent (has solutions) if and only if $ \textbf{b} $ is in the column space of $ \textbf{A} $. So $ \textbf{b} \in col(\textbf{A})$

  #### proof: 
  
  Write the equation $ \textbf{Ax=b} $ as a sum of column vectors, with $ \textbf{A} = [\textbf{a}_1 \ \textbf{a}_2 \cdots \textbf{a}_n] $   
  
  $ 
  \begin{bmatrix}
  a_{11} & a_{12} & \cdots & a_{1n} \\
  a_{21} & a_{22} & \cdots & a_{2n} \\
  \vdots & \vdots & \ddots & \vdots \\
  a_{m1} & a_{m2} & \cdots & a_{mn}
  \end{bmatrix}
  \begin{bmatrix}
  x_{1} \\
  x_{2} \\
  \vdots \\
  x_{n}
  \end{bmatrix}
      =
  \begin{bmatrix}
  b_{1} \\
  b_{2} \\
  \vdots \\
  b_{n}
  \end{bmatrix}
  $
  
  $ \implies x_1\textbf{a}_1 + x_2\textbf{a}_2 + \cdots + x_n\textbf{a}_n = \textbf{b} $

  Therefore we conclude that $ \textbf{b} $ is a linear combination of the column vectors of $ \textbf{A} $.

- Suppose that the linear system $ \textbf{Ax = b} $ is consistent and let $ \textbf{p} $ be a solution. Then any other solution $ \textbf{q} $ of the system $ \textbf{Ax = b} $ can be written in the form $ \textbf{q = p + v} $, for some vector $ \textbf{v} $ that is a solution to the homogeneous system $ \textbf{Ax = 0} $.
