## LU Decomposition

## PLU Decomposition

Let $ \textbf{A} $ be an $ m \times n $ matrix. Then there exists a permutation matrix $ \textbf{P} $ such that $ \textbf{A = PLU} $, where $ \textbf{L} $ is a lower triangular $ m \times m $ matrix with 1s on the diagonal, $ \textbf{U} $ is an $ m \times n $ upper triangular matrix and $ \textbf{P} $ is an $ m \times m $ matrix known as the permutation matrix (a permutation of the rows of the identity matrix).



In [24]:
A = np.array([[2, 5, 8, 7], [5, 2, 2, 8], [7, 5, 6, 6], [5, 4, 4, 8]])

p, l, u = sp.linalg.lu(A)

print(A, '\n')

print(u, '\n')

print(p, '\n')

print(p @ l @ u)

[[2 5 8 7]
 [5 2 2 8]
 [7 5 6 6]
 [5 4 4 8]] 

[[ 7.          5.          6.          6.        ]
 [ 0.          3.57142857  6.28571429  5.28571429]
 [ 0.          0.         -1.04        3.08      ]
 [ 0.          0.          0.          7.46153846]] 

[[0. 1. 0. 0.]
 [0. 0. 0. 1.]
 [1. 0. 0. 0.]
 [0. 0. 1. 0.]] 

[[2. 5. 8. 7.]
 [5. 2. 2. 8.]
 [7. 5. 6. 6.]
 [5. 4. 4. 8.]]
