## PLU Decomposition

$ \textbf{LU} $ decomposition is not possible for every matrix, since row swaps may be necessary to reduce it to row echelon form. For such a matrix $ \textbf{A} $, we may perform the row swaps first, then find an $ \textbf{LU} $ decomposition of the resulting matrix. 

Let $ \textbf{T} = \textbf{E}_1 \textbf{E}_2 \cdots \textbf{E}_k $ be the product of the elementary matrices that swap the rows of $ \textbf{A} $, therefore the following exists

$ \textbf{TA} = \textbf{LU} $ 

If $ \textbf{P} = \textbf{T}^{-1} $

Then we can write 

$ \textbf{A = PLU} $

Every square matrix has a $ \textbf{PLU} $ decomposition 

### PLU decomposition and Systems of Linear Equations

We want to solve the system of linear equations

$ \textbf{Ax} = \textbf{b} $ 

This can be solved by using the $ \textbf{A} = \textbf{PLU} $ decomposition 

$ \therefore \ \ \textbf{PLUx} = \textbf{b} $ 

$ \Rightarrow \ \textbf{LUx} = \textbf{Tb} $

### Example

Find the $ \textbf{PLU} $ decomposition of $ \textbf{A} $ and use it to solve the system $ \textbf{Ax} = \textbf{b} $, where

$
\textbf{A} =
\begin{bmatrix}
0 & 4 & 1 \\
4 & 1 & 4 \\
8 & 1 & 2
\end{bmatrix}
\ \ \ , \ \ 
\textbf{b} =
\begin{bmatrix}
1 \\
0 \\
2
\end{bmatrix}
$

**Solution:**

We can't use $ \textbf{LU} $ decomposition because the first element in $ \textbf{A} $ is a 0 and we would need to swap the row.

We have to multiply both sides of $ \textbf{Ax} = \textbf{b} $ with a matrix $ \textbf{P} $ that does the row swapping.

To swap rows 1 and 3, use the following elementary matrix

$
\textbf{T} =
\begin{bmatrix}
0 & 0 & 1 \\
0 & 1 & 0 \\
1 & 0 & 0
\end{bmatrix}
\ \ \ \ \ \Rightarrow \ \ 
\textbf{P} = \textbf{T}^{-1} = 
\begin{bmatrix}
0 & 0 & 1 \\
0 & 1 & 0 \\
1 & 0 & 0
\end{bmatrix}
$

$
\textbf{TA} =
\begin{bmatrix}
0 & 0 & 1 \\
0 & 1 & 0 \\
1 & 0 & 0
\end{bmatrix}
\begin{bmatrix}
0 & 4 & 1 \\
4 & 1 & 4 \\
8 & 1 & 2
\end{bmatrix}
    =
\begin{bmatrix}
8 & 1 & 2 \\
4 & 1 & 4 \\
0 & 4 & 1
\end{bmatrix}
$

This matrix does have an $ \textbf{LU} $ decomposition.

Convert it to row echelon form, by doing the following operations, while simultaneously applying these operations on the elementary matrix (start with I)

- divide $ R_1 $ by 8
- $ R_2 - 4 R_1 $
- $ 2 R_2 $
- $ R_3 - 4 R_2 $
- $ -\frac{1}{23} R_3 $

These operations give

$
\textbf{U} = 
\begin{bmatrix}
1 & \frac{1}{8} & \frac{1}{4} \\
0 & 1 & 6 \\
0 & 0 & 1
\end{bmatrix}
\ \ \ , \ \
\textbf{L} = 
\begin{bmatrix}
8 & 0 & 0 \\
4 & \frac{1}{2} & 0 \\
0 & 4 & -23
\end{bmatrix}
$

$ 
\therefore \textbf{A} = \textbf{PLU} =  
\begin{bmatrix}
0 & 0 & 1 \\
0 & 1 & 0 \\
1 & 0 &  0
\end{bmatrix}
\begin{bmatrix}
8 & 0 & 0 \\
4 & \frac{1}{2} & 0 \\
0 & 4 & -23
\end{bmatrix}
\begin{bmatrix}
1 & \frac{1}{8} & \frac{1}{4} \\
0 & 1 & 6 \\
0 & 0 & 1
\end{bmatrix}
$

Now we can solve the system of linear equations

$ \textbf{LUx} = \textbf{Tb} $ 

$   
\begin{bmatrix}
8 & 0 & 0 \\
4 & \frac{1}{2} & 0 \\
0 & 4 & -23
\end{bmatrix}
\begin{bmatrix}
1 & \frac{1}{8} & \frac{1}{4} \\
0 & 1 & 6 \\
0 & 0 & 1
\end{bmatrix}
\begin{bmatrix}
x_1 \\
x_2 \\
x_3
\end{bmatrix}
    =
\begin{bmatrix}
0 & 0 & 1 \\
0 & 1 & 0 \\
1 & 0 &  0
\end{bmatrix}
\begin{bmatrix}
1 \\
0 \\
2 
\end{bmatrix}
$

let $ \textbf{y} = \textbf{Ux} $ 

$   
\begin{bmatrix}
8 & 0 & 0 \\
4 & \frac{1}{2} & 0 \\
0 & 4 & -23
\end{bmatrix}
\begin{bmatrix}
y_1 \\
y_2 \\
y_3
\end{bmatrix}
    =
\begin{bmatrix}
2 \\
0 \\
1 
\end{bmatrix}
$

$ \Rightarrow \ \ y_1=\frac{1}{4}, \ \ y_2=-2, \ \ y_3=\frac{-9}{23} $

Now solve $ \textbf{y} = \textbf{Ux} $

$   
\begin{bmatrix}
\frac{1}{4} \\
-2 \\
\frac{-9}{23}
\end{bmatrix}
    =
\begin{bmatrix}
1 & \frac{1}{8} & \frac{1}{4} \\
0 & 1 & 6 \\
0 & 0 & 1
\end{bmatrix}
\begin{bmatrix}
x_1 \\
x_2 \\
x_3
\end{bmatrix}
$

$ \Rightarrow \ \ \ x_1=\frac{7}{23}, \ \ x_2=\frac{8}{23}, \ \ x_3=\frac{-9}{23} $ 

### Example using SciPy

In [1]:
import numpy as np
import scipy as sp

A = np.array([[2, 5, 8, 7], [5, 2, 2, 8], [7, 5, 6, 6], [5, 4, 4, 8]])

p, l, u = sp.linalg.lu(A)

print(A, '\n')

print(u, '\n')

print(p, '\n')

print(p @ l @ u)

[[2 5 8 7]
 [5 2 2 8]
 [7 5 6 6]
 [5 4 4 8]] 

[[ 7.          5.          6.          6.        ]
 [ 0.          3.57142857  6.28571429  5.28571429]
 [ 0.          0.         -1.04        3.08      ]
 [ 0.          0.          0.          7.46153846]] 

[[0. 1. 0. 0.]
 [0. 0. 0. 1.]
 [1. 0. 0. 0.]
 [0. 0. 1. 0.]] 

[[2. 5. 8. 7.]
 [5. 2. 2. 8.]
 [7. 5. 6. 6.]
 [5. 4. 4. 8.]]
