## QR Decomposition

The $ \textbf{QR} $ decomposition allows us to express a matrix having linearly independent columns as the product of 

- a matrix $ \textbf{Q} $ having orthonormal columns and 
- an upper triangular matrix $ \textbf{R} $

$ \textbf{A} = \textbf{QR} $

The Gram-Schmidt process is a procedure used to transform a set of linearly independent vectors into a set of orthonormal vectors.

In the case of a matrix $ \textbf{A} $, denote its columns $ \textbf{A}_1, \textbf{A}_2, \cdots, \textbf{A}_k $. If these columns are linearly independent, they can be transformed into a set of orthonormal column vectors $ \textbf{Q}_1, \textbf{Q}_2, \cdots, \textbf{Q}_k $ by using the Gram-Schmidt process

In [26]:
A = np.array([[12, -51, 4], [6, 167, -68], [-4, 24, -41]])
Q, R = sp.linalg.qr(A)

print(A, '\n')

print(Q, '\n')

print(R, '\n')

print(Q @ R)

[[ 12 -51   4]
 [  6 167 -68]
 [ -4  24 -41]] 

[[-0.85714286  0.39428571  0.33142857]
 [-0.42857143 -0.90285714 -0.03428571]
 [ 0.28571429 -0.17142857  0.94285714]] 

[[ -14.  -21.   14.]
 [   0. -175.   70.]
 [   0.    0.  -35.]] 

[[ 12. -51.   4.]
 [  6. 167. -68.]
 [ -4.  24. -41.]]
