## Cholesky Decomposition

The Cholesky decomposition is a decomposition of a Hermitian, positive-definite matrix into the product of a lower triangular matrix $ \textbf{L} $ and its conjugate transpose, $ \textbf{L}^{*} $, which is useful for efficient numerical solutions such as Monte Carlo simulations. 

$ \textbf{A} = \textbf{L} \textbf{L}^{*} $

The Cholesky decomposition is roughly twice as efficient as the LU decomposition for solving systems of linear equations and is often used as a fast way of solving sets of linear equations, $ \textbf{Ax = b} $ (when $ \textbf{A} $ is both Hermitian/symmetric and positive-definite).

When $ \textbf{A} $ is a real matrix (hence symmetric positive-definite), the factorization may be written

$ \textbf{A} = \textbf{L} \textbf{L}^{T} $

In [ ]:
A = np.array([[6, 3, 4, 8], [3, 6, 5, 1], [4, 5, 10, 7], [8, 1, 7, 25]])

L = sp.linalg.cholesky(A, lower = True)
L_T = sp.linalg.cholesky(A, lower = False)

print(A, '\n')

print(L, '\n')

print(L_T, '\n')

print(L @ L_T)

[[ 6  3  4  8]
 [ 3  6  5  1]
 [ 4  5 10  7]
 [ 8  1  7 25]] 

[[ 2.44948974  0.          0.          0.        ]
 [ 1.22474487  2.12132034  0.          0.        ]
 [ 1.63299316  1.41421356  2.30940108  0.        ]
 [ 3.26598632 -1.41421356  1.58771324  3.13249102]] 

[[ 2.44948974  1.22474487  1.63299316  3.26598632]
 [ 0.          2.12132034  1.41421356 -1.41421356]
 [ 0.          0.          2.30940108  1.58771324]
 [ 0.          0.          0.          3.13249102]] 

[[ 6.  3.  4.  8.]
 [ 3.  6.  5.  1.]
 [ 4.  5. 10.  7.]
 [ 8.  1.  7. 25.]]
