# Linear Algebra - Matrices

## Matrix Addition

To sum matrices they have to be of the same dimension.

If $ \textbf{A} $ and $ \textbf{B} $ are two matrices of the same dimension and $ k $ is a scalar

1. $ \textbf{A + B = B + A} $  &emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;(Commutative)
   
2. $ \textbf{(A + B) + C = A + (B + C)} $  &emsp; (Associative)
   
3. $ k(\textbf{A} + \textbf{B}) = k \textbf{A} + k \textbf{B} $

## Matrix Multiplication

If $ \textbf{A} $ and $ \textbf{B} $ are two matrices of the same dimension and $ k $ is a scalar

1. $ \textbf{AB} \ne \textbf{BA} $  &emsp;&emsp;&emsp;&emsp;&emsp;&emsp;(Not Commutative)
   
2. $ \textbf{(AB)C} = \textbf{A(BC)} $  &emsp;&emsp; (Associative)

3. $ \textbf{(kA)B = k(AB) = A(kB)} $ 
   
4. $ \textbf{A(B + C) = AB + AC} $ and $ \textbf{(A + B)C = AC + BC} $

## Trace of a Matrix

The trace of an $ n \times n $ matrix $ \textbf{A} $ is defined as the sum of the main diagonal elements

$ 
\textbf{A} = \sum \limits_{i=1}^{n} A_{ii}
$

With rules

1. $ Tr(k\textbf{A}) = k Tr(\textbf{A}) $

2. $ Tr(\textbf{A} + \textbf{B}) = Tr(\textbf{A}) + Tr(\textbf{B}) $
   
3. $ Tr(\textbf{A}^T) = Tr(\textbf{A}) \ \ \ \ \ \ \ \ $           [because the diagonal is the same for both]

4. $ Tr(\textbf{AB}) = Tr(\textbf{BA}) $

## Row Echelon Form

A matrix is in row echelon form if the following conditions are true

- The row echelon form of a matrix is not unique, a matrix can have many row echelon forms.

- All the entries beneath a leading 1 on a row is 0.

- If a row does not consist entirely of zeros, then the first nonzero number in the row is 1.

- All zero rows are the bottom of the matrix

- In any two successive rows that do not consist entirely of zeros, the leading 1 in the lower row occurs farther to the right than the leading 1 in the higher row

  $
  \begin{bmatrix}
  \color{orange}1 & 4 \\
  \color{red}0 & \color{orange}1 
  \end{bmatrix}
  \ \ \ \ \
  $
  $
  \begin{bmatrix}
  \color{orange}1 & 5 & 2\\
  \color{red}0 & \color{orange}1 & 4\\
  \color{red}0 & \color{red}0 & \color{red}0
  \end{bmatrix}
  \ \ \ \ \
  $
  $
  \begin{bmatrix}
  \color{orange}1 & 3 & 2\\
  \color{red}0 & \color{orange}1 & 7\\
  \color{red}0 & \color{red}0 & \color{orange}1
  \end{bmatrix}
  \ \ \ \ \
  $
  $
  \begin{bmatrix}
  \color{orange}1 & 3 & 2 & 4 & 7\\
  \color{red}0 & \color{orange}1 & 7 & 5 & 2\\
  \color{red}0 & \color{red}0 & \color{orange}1 & 7 & 5\\
  \color{red}0 & \color{red}0 & \color{red}0 & \color{red}0 & \color{red}0
  \end{bmatrix}
  $

### Gaussian Elimination

Row operations to convert a matrix into row echelon form is called Gaussian elimination. 

The three types of elementary row operations are:

- **Multiply a row by a nonzero number**

- **Interchange two rows**

- **Add a multiple of a row to another row**

Process:-

1- Locate the leftmost column that does not consist entirely of zeros.

2- Interchange the top row with another, if necessary, to bring a nonzero entry to the top of the column found in step 1.

3- If the entry that is now at the top of the column found in step 1 is a, multiply multiply the first row by 1/a in order to introduce a leading 1.

4- Add suitable multiples of the top row to the rows below so that all entries below the leading 1 becomes zeros.

5- Now cover the top row in the matrix and begin again with step 1 applied to the submatrix that remains. Continue int this way until the entire matrix is in row echelon form.

### Example
Use Gaussian elimination to convert this matrix to REF

$
\begin{bmatrix}
2 & 4 & 6 \\
2 & 4 & 2 \\
1 & 3 & 1
\end{bmatrix}
$

To obtain a leading 1 on $ R_1 $, divide $ R_1 $ by 2

$
\begin{bmatrix}
1 & 2 & 3 \\
2 & 4 & 2 \\
1 & 3 & 1
\end{bmatrix}
$

Set the leading element in $ R_2 $ to 1 by dividing it by 2

$
\begin{bmatrix}
1 & 2 & 3 \\
1 & 2 & 1 \\
1 & 3 & 1
\end{bmatrix}
$

Now we can create a leading 0 on $ R_2 $ by subtracting $ R_1 $ from $ R_2 $

$
\begin{bmatrix}
1 & 2 & 3 \\
0 & 0 & -2 \\
1 & 3 & 1
\end{bmatrix}
$

Two leading 0's is a good fit for $ R_3 $, so swap $ R_2 $ with $ R_3 $

$
\begin{bmatrix}
1 & 2 & 3 \\
1 & 3 & 1 \\
0 & 0 & -2
\end{bmatrix}
$

Divide $ R_3 $ by -2

$
\begin{bmatrix}
1 & 2 & 3 \\
1 & 3 & 1 \\
0 & 0 & 1
\end{bmatrix}
$

Finally, To get a leading 0 on $ R_2 $, subtract $ R_1 $ from it

$
\begin{bmatrix}
1 & 2 & 3 \\
0 & 1 & -2 \\
0 & 0 & 1
\end{bmatrix}
$

### REF using Sympy

In [2]:
import numpy as np
from sympy import Matrix

A = np.array([[2, -3, -2], [1, -4, 2], [-3, 5, -1]]);

# Convert to sympy matrix
A_Mat = Matrix(A)

# Get REF (Row Echelon Form)
REF = A_Mat.echelon_form()

print(np.array(REF), '\n')

[[2 -3 -2]
 [0 -5 6]
 [0 0 34]] 



## Reduced Row Echelon Form

- Similar to Row Echelon form, with the extra codition that each column with a leading 1 must have 0's above it

- Matrices must only have one reduced row echelon form; the reduced row echelon form is unique.

- Every matrix can be transformed into a reduced row echelon form by a process called Gauss-Jordan elimination

- If a square matrix $ \textbf{A} $ has linearly independent colums, then the reduced row echelon form of the matrix is the identity matrix $ \textbf{I} $

  $
  \begin{bmatrix}
  \color{orange}1 & \color{red}0 \\
  \color{red}0 & \color{orange}1 
  \end{bmatrix}
  \ \ \ \ \ \
  $
  $
  \begin{bmatrix}
  \color{orange}1 & \color{red}0 & 2 \\
  \color{red}0 & \color{orange}1 & 4 \\
  \color{red}0 & \color{red}0 & \color{red}0
  \end{bmatrix}
  \ \ \ \ \ \
  $
  $
  \begin{bmatrix}
  \color{orange}1 & \color{red}0 & 0 \\
  \color{red}0 & \color{orange}1 & \color{red}0 \\
  0 & \color{red}0 & \color{orange}1
  \end{bmatrix}
  \ \ \ \ \ \
  $
  $
  \begin{bmatrix}
  0 & \color{orange}1 & 5 & \color{red}0 & 0 & 0 & 3 & 9 & 0 & 7 \\
  0 & \color{red}0 & 0 & \color{orange}1 & \color{red}0 & 0 & 5 & 7 & 0 & 5 \\
  0 & 0 & 0 & \color{red}0 & \color{orange}1 & \color{red}0 & 7 & 3 & 0 & 3 \\
  0 & 0 & 0 & 0 & \color{red}0 & \color{orange}1 & 2 & 6 & \color{red}0 & 9 \\
  0 & 0 & 0 & 0 & 0 & \color{red}0 & 0 & 0 & \color{orange}1 & 2
  \end{bmatrix}
  $

### Gauss-Jordan Elimination

Gauss-Jordan Elimination is used to convert any matrix to reduced row echelon form.

It uses the same three elementary operations as Gaussian elimination.

It also follows a similar recipe as Gaussian elimination, but with an added extra step 6 below,

  1- Locate the leftmost column that does not consist entirely of zeros.

  2- Interchange the top row with another, if necessary, to bring a nonzero entry to the top of the column found in step 1.

  3- If the entry that is now at the top of the column found in step 1 is a, multiply multiply the first row by 1/a in order to introduce a leading 1.

  4- Add suitable multiples of the top row to the rows below so that all entries below the leading 1 becomes zeros.

  5- Now cover the top row in the matrix and begin again with step 1 applied to the submatrix that remains. Continue int this way until the entire matrix is in row echelon form.

  6- Beginnign with the last nonzero row and working upward, add suitable multiples of each row to the rows above to introduce zeros above the leading 1's.

### Example

Rewrite this following matrix in RREF

$
\begin{bmatrix}
2 & -2 & 4 \\
6 & -2 & 3 \\
3 & -2 & 4
\end{bmatrix}
$

We need a leading 1 on $ R_1 $, divide $ R_1 $ by 2

$
\begin{bmatrix}
1 & -1 & 2 \\
6 & -2 & 3 \\
3 & -2 & 4
\end{bmatrix}
$

Create a leading 0 on $ R_3 $ by subtracting $ 3 \times R_1 $ from $ R_3 $

$
\begin{bmatrix}
1 & -1 & 2 \\
6 & -2 & 3 \\
0 & 1 & -2
\end{bmatrix}
$

Create a leading 0 on $ R_2 $ by subtracting $ 6 \times R_1 $ from $ R_2 $

$
\begin{bmatrix}
1 & -1 & 2 \\
0 & 4 & -9 \\
0 & 1 & -2
\end{bmatrix}
$

We need a 0 above the leading number on $ R_2 $, add $ R_3 $ to $ R_1 $

$
\begin{bmatrix}
1 & 0 & 0 \\
0 & 4 & -9 \\
0 & 1 & -2
\end{bmatrix}
$

We need a leading 0 on $ R_3 $, apply $ -4 \times R_3 + R_2 $ 

$
\begin{bmatrix}
1 & 0 & 0 \\
0 & 4 & -9 \\
0 & 0 & -1
\end{bmatrix}
$

We need a leading 1 on $ R_3 $, multiple by -1

$
\begin{bmatrix}
1 & 0 & 0 \\
0 & 4 & -9 \\
0 & 0 & 1
\end{bmatrix}
$

We need a 0 above the leading 1 of $ R_3 $, therefore add $ 9 \times R_3 $ to $ R_2 $

$
\begin{bmatrix}
1 & 0 & 0 \\
0 & 4 & 0 \\
0 & 0 & 1
\end{bmatrix}
$

All that remains is to divide $ R_2 $  by 4

$
\begin{bmatrix}
1 & 0 & 0 \\
0 & 1 & 0 \\
0 & 0 & 1
\end{bmatrix}
$

### RREF with Sympy

In [3]:
import numpy as np
from sympy import Matrix

A = np.array([[2, -3, -2], [1, -4, 2], [-3, 5, -1]]);

# Convert to sympy matrix
Mat = Matrix(A)

# Get RREF (Reduced Row Echelon Form)
RREF = Mat.rref()[0]

print(np.array(RREF))

[[1 0 0]
 [0 1 0]
 [0 0 1]]


## Pivot

- The positions of the leading 1's in a row echelon or reduced row echelon form matrix are the pivot positions.

- A nonzero entry in a pivot position is a pivot.

  $
  \begin{bmatrix}
  \color{orange}1 & -3 & 4 & 7\\
  0 & \color{orange}1 & 2 & 2\\
  0 & 0 & \color{orange}8 & 5
  \end{bmatrix}
  $

  1, 1 and 8 in the diagonals are the pivot points of the matrix.

- The columns containing the leading 1's in a row echelon or reduced row echelon form matrix are the pivot columns of the matrix.
   
- The rows containing the leading 1's are the pivot rows.

## Transpose Rules

Let $ \textbf{A} $ and $ \textbf{B} $ be matrices of appropriate sizes and $ k $ a scalar. The following hold:

1. $ (\textbf{A}^{T})^{T} = \textbf{A} $
   
2. $ \textbf{(A + B)}^T = \textbf{A}^T + \textbf{B}^T $
   
3. $ (k\textbf{A})^T = k\textbf{A}^T $
   
4. $ (\textbf{AB})^{T} = \textbf{B}^{T}\textbf{A}^T $

In [16]:
# Proof

A = np.array([[4, 1, 7], [6, 5, 9], [2, 6, 7]])

B = np.array([[6, 4, 9], [1, 4, 7], [3, 0, 6]])

# 1.
print(((A.T).T == A).all())

# 2.
print((((A + B).T == (A.T + B.T))).all())

# 3. 
print((((5 * A).T) == (5 * A.T)).all())

# 4. 
print( (((A * B).T) == (B.T * A.T)).all())

True
True
True
True


## Inverse Matrix

- The inverse of a matrix $ \textbf{A} $ is a matrix $ \textbf{A}^{-1} $ such that $ \textbf{A}^{-1}\textbf{A} = \textbf{I} $

- The inverse of a matrix is unique for that matrix.
  
- A square matrix $ \textbf{A} $ is invertible if and only if $ |\textbf{A}| \neq 0 $

- A square matrix $ \textbf{A} $ is invertible if the rows of $ \textbf{A} $ are independent

- A square matrix $ \textbf{A} $ is invertible if the columns of $ \textbf{A} $ are independent

- A square matrix $ \textbf{A} $ is invertible if and only if $ \lambda = 0 $ is not an eigenvalue of $ \textbf{A} $.

- Not every matrix is invertible.

- The inverse matrix can be calculated using 

  $ \textbf{A}^{-1} = \dfrac{\large{1}}{\large{|\textbf{A}|}} Adj(\textbf{A}) $ 

  where $ Adj(\textbf{A}) $ is the Adjoint matrix and is defined as $ Adj(\textbf{A}) = (cofactor(\textbf{A}))^{T} $  

- Let A and B be invertible matrices, the following identities hold:

  - $ (\textbf{A}^{−1})^{−1} = \textbf{A} $

  - $ (\textbf{A}^{T})^{−1} = (\textbf{A}^{−1})^{T} $

  - $ (\textbf{AB})^{−1} = \textbf{B}^{−1} \textbf{A}^{−1} $

  - $ (k\textbf{A})^-1 = \dfrac{1}{k} \textbf{A}^{-1} $

### Inverse Matrix using SciPy

In [17]:
# setup

A = np.array([[0, -3, -2], [1, -4, -2], [-3, 4, 1]])

B = np.array([[1, 2, 3], [0, 1, 4], [5, 6, 0]])

A_inv = sp.linalg.inv(A)

B_inv = sp.linalg.inv(B)


# 1.
print((np.round(sp.linalg.inv(A_inv), 4) == A).all())

# 2. 
print((np.round(sp.linalg.inv(np.matmul(A, B)), 4) == np.round(np.matmul(B_inv, A_inv), 4)).all())

# 3. 
print((np.round(sp.linalg.inv(A.T), 4) == np.round(sp.linalg.inv(A).T, 4)).all())

True
True
True


### Inverse Matrix using RREF

Also known as the 'inversion algorithm'. Let $ A $ be an $ n \times n $ square matrix. Then the matrix $ \textbf{A} $ is invertible only if its reduced row echelon form is the identity matrix $ \textbf{I} $.

Proof:

By definition $ \textbf{A}^{-1}\textbf{A} = I $

Let $ E_1, \ E_2, \ E_3, \ ..., \ E_n $ be the set of Gaussian-Jordan transformations that converts $ \textbf{A} $ to an identity matrix $ \textbf{I} $

$ \implies E_1 \ E_2 \ E_3 \ ... \ E_n \ \textbf{A} = \textbf{I} $

multiply both sides by $ \textbf{A}^{-1} $

$ \implies E_1 \ E_2 \ E_3 \ ... \ E_n \ \textbf{A} \textbf{A}^{-1} = \textbf{I} \textbf{A}^{-1} $

$ \implies E_1 \ E_2 \ E_3 \ ... \ E_n \ \textbf{I} = \textbf{A}^{-1} $

$ \therefore \textbf{A}^{-1} = E_1 \ E_2 \ E_3 \ ... \ E_n $

### Example
Find the inverse of the following matrix by transforming it to reduce row echelon form

$
\begin{bmatrix}
1 & 2 & 3 \\
2 & 5 & 3 \\
1 & 0 & 8
\end{bmatrix}
$

Start by augmenting the matrix with the identity matrix


$
\begin{bmatrix}
1 & 2 & 3 & | & 1 & 0 & 0 \\
2 & 5 & 3 & | & 0 & 1 & 0 \\
1 & 0 & 8 & | & 0 & 0 & 1 
\end{bmatrix}
$

Apply Gauss-Jordan transformations such that the left hand of the matrix becomes the identity matrix

- $ R_2 : R_2 - 2 R_1 $
- $ R_3 : R_3 - R_1 $

  $
  \begin{bmatrix}
  1 & 2 & 3 & | & 1 & 0 & 0 \\
  0 & 1 & -3 & | & -2 & 1 & 0 \\
  0 & -2 & 5 & | & -1 & 0 & 1 
  \end{bmatrix}
  $

- $ R_1 : R_1 - 2 R_2 $
- $ R_3 : R_3 + 2 R_2 $

  $
  \begin{bmatrix}
  1 & 0 & 9 & | & 5 & -2 & 0 \\
  0 & 1 & -3 & | & -2 & 1 & 0 \\
  0 & 0 & -1 & | & -5 & 2 & 1 
  \end{bmatrix}
  $

- $ R_1 : R_1 + 9 R_3 $
- $ R_2 : R_2 - 3 R_3 $
- $ R_3 : - 1 R_3 $

  $
  \begin{bmatrix}
  1 & 0 & 0 & | & -40 & 16 & 9 \\
  0 & 1 & 0 & | & 13 & -5 & -3 \\
  0 & 0 & 1 & | & 5 & -2 & -1 
  \end{bmatrix}
  $

$ \therefore $ the inverse matrix is 

  $
  \begin{bmatrix}
  -40 & 16 & 9 \\
  13 & -5 & -3 \\
  5 & -2 & -1 
  \end{bmatrix}
  $

In [18]:
# let's check the invese using SciPy
A = np.array([[1, 2, 3], [2, 5, 3], [1, 0, 8]]);

# Convert to sympy matrix
A_Mat = Matrix(A)

# Get RREF (Reduced Row Echelon Form)
RREF = A_Mat.rref()[0]

print(np.array(RREF), '\n')

print(sp.linalg.inv(A))

[[1 0 0]
 [0 1 0]
 [0 0 1]] 

[[-40.  16.   9.]
 [ 13.  -5.  -3.]
 [  5.  -2.  -1.]]


## Diagonally Dominant Matrix

- A matrix is diagonally dominant if each $ |\textbf{a}_{ii}| $ on the diagonal is larger than the sum of magnitudes along the rest of the row i.
  
  $ |\textbf{a}_{ii}| \gt \sum \limits_{j \ne i}^{n} |a_{ij}| $

- A diagonally dominant matrix is always invertible. But a non-diagonally dominant matrix may or may not be invertible 

### Example

- The following matrix is diagonally dominant since the diagonal elements are greater than the sum of the rest of their rows, therefore this matrix has an inverse.

  $ 
  \begin{bmatrix}
  4 & 1 & 2 \\
  1 & 3 & 1 \\
  0 & 1 & 2 
  \end{bmatrix}
  $

  - 4 > 1 + 2
  
  - 3 > 1 + 1
  
  - 2 > 0 + 1

- The following matrix is non-diagonally dominant, but it is still invertible

  $
  \begin{bmatrix}
  1 & -4 & 2 \\
  -2 & 1 & 3 \\
  2 & 6 & 8 
  \end{bmatrix}
  $

  - 1 < 4 + 2
  
  - 1 < 2 + 3
  
  - 8 = 2 + 6

- The following matrix is not diagonally dominant, since the first diagonal element is less than the sum of the other elements on its row, and it is also non-invertible

  $
  \begin{bmatrix}
  1 & 6 & 4 \\
  2 & 4 & -1 \\
  -1 & 2 & 5 
  \end{bmatrix}
  $

  - 1 < 6 + 4
  
  - 4 > 2 + 1
  
  - 5 > 2 + 1

## Determinant of a Matrix

Given an $ n \times n $ matrix $ \textbf{A} $, the determinant $ \textbf{det(A)} $ or $ |\textbf{A}| $ is a scalar quantity which is defined for a $ 2 \times 2 $ and can be extended for higher dimensions 

$ 
|\textbf{A}| =
\begin{vmatrix}
a & b \\
c & d 
\end{vmatrix}
    =
ad - bc
$

### Rules

- Any matrix $ \textbf{A} $ that has one or more rows or columns with filled only with 0's, will have a determinant of 0

  $ 
  \begin{bmatrix}
  4 & 1 & 2 \\
  \color{red}0 & \color{red}0 & \color{red}0 \\
  0 & 1 & 2 
  \end{bmatrix}
   \ \ or \ \
  \begin{bmatrix}
  4 & 1 & \color{red}0 \\
  1 & 3 & \color{red}0 \\
  0 & 1 & \color{red}0 
  \end{bmatrix}
  \ \ \ \ \
  \implies
  |\textbf{A}| = 0
  $

- If $ \textbf{A} $ is a square matrix with two rows (or two columns) that are equal then its determinant will be 0

  $ 
  \begin{bmatrix}
  4 & 1 & 2 \\
  \color{red}5 & \color{red}8 & \color{red}2 \\
  \color{red}5 & \color{red}8 & \color{red}2 
  \end{bmatrix}
  \ \ or \ \
  \begin{bmatrix}
  4 & \color{red}1 & \color{red}1 \\
  1 & \color{red}3 & \color{red}3 \\
  0 & \color{red}1 & \color{red}1 
  \end{bmatrix}
  \ \ \ \ \
  \implies
  |\textbf{A}| = 0
  $

- The determinant of the transpose of a matrix is equal to the determinant of the matrix

    $ |\textbf{A}^T| = |\textbf{A}| $
  
- If matrix $ A $ is invertible, then

    $ |\textbf{A}^{-1}| = \Large{\frac{1}{|\textbf{A}|}} $

- The determinant of the matrix $ \textbf{A} $ raised ot power $ m $ is related to the determinant of the matrix as follows

    $ |\textbf{A}^m| = |\textbf{A}|^m $

- The determinant of the adjoint of a matrix is related to the determinant of the matrix as follows

    $ |Adj(\textbf{A})| = |\textbf{A}|^{n-1} $
  
- Let $ \textbf{A} $ and $ \textbf{B} $ be square matrices, then
    
    $ \textbf{|AB|} = \textbf{|A||B|} $

- Suppose that $ \textbf{A} $ is a square matrix and let $ \textbf{B} $ be the matrix obtained by interchanging two rows of $ \textbf{A} $, then 

    $ \textbf{|B|} = −\textbf{|A|} $

    $ 
    \textbf{A} = 
    \begin{bmatrix}
    a_{11} & a_{12} & a_{13} \\
    a_{21} & a_{22} & a_{23} \\
    a_{31} & a_{32} & a_{33} 
    \end{bmatrix}
    , \ \ \ \ \
    \textbf{B} = 
    \begin{bmatrix}
    a_{11} & a_{12} & a_{13} \\
    \color{red}a_{31} & \color{red}a_{32} & \color{red}a_{33} \\
    \color{red}a_{21} & \color{red}a_{22} & \color{red}a_{23}
    \end{bmatrix}
    \ \ \ \ \
    \implies
    \textbf{|B|} = −\textbf{|A|} 
    $  

- Let $ \textbf{A} $ be a square matrix, and let $ \textbf{B} $ be the matrix obtained by multiplying a row of $ \textbf{A} $ by $ \beta $, then

    $ \textbf{|B|} = \beta|\textbf{A}| $

    $ 
    \textbf{A} = 
    \begin{bmatrix}
    a_{11} & a_{12} & a_{13} \\
    a_{21} & a_{22} & a_{23} \\
    a_{31} & a_{32} & a_{33} 
    \end{bmatrix}
    , \ \ \ \ \
    \textbf{B} = 
    \begin{bmatrix}
    a_{11} & a_{12} & a_{13} \\
    \color{red}\beta \ a_{21} & \color{red}\beta \ a_{22} & \color{red}\beta \ a_{23} \\
    a_{31} & a_{32} & a_{33} 
    \end{bmatrix}
    \ \ \ \ \
    \implies
    \textbf{|B|} = \beta|\textbf{A}|
    $ 

- Let $ \textbf{A} $ be a square matrix, and let $ \textbf{B} $ be the matrix obtained from $ \textbf{A} $ by adding $ \beta $ times the kth row to the jth row, then 

    $ \textbf{|B|} = \textbf{|A|} $

    $ 
    \textbf{A} = 
    \begin{bmatrix}
    a_{11} & a_{12} & a_{13} \\
    a_{21} & a_{22} & a_{23} \\
    a_{31} & a_{32} & a_{33} 
    \end{bmatrix}
    , \ \ \ \ \
    \textbf{B} = 
    \begin{bmatrix}
    a_{11} & a_{12} & a_{13} \\
    a_{21} & a_{22} & a_{23} \\
    \color{red}a_{31}+\beta a_{21} & \color{red}a_{32}+\beta \ a_{22} & \color{red}a_{33} + \beta \ a_{23}
    \end{bmatrix}
    \ \ \ \ \
    \implies
    \textbf{|B|} = \textbf{|A|}
    $ 

- Let $ \textbf{A} $ be an $ n \times n $ square matrix, then 

    $ \beta|\textbf{A}| = \beta^{n} |\textbf{A}| $

    $ 
    \textbf{A} = 
    \begin{bmatrix}
    a_{11} & a_{12} & a_{13} \\
    a_{21} & a_{22} & a_{23} \\
    a_{31} & a_{32} & a_{33} 
    \end{bmatrix}
    , \ \ \ \ \
    \beta \textbf{A} = 
    \begin{bmatrix}
    \color{red} \beta \ a_{11} & \color{red} \beta \ a_{12} & \color{red} \beta \ a_{13} \\
    \color{red} \beta \ a_{21} & \color{red} \beta \ a_{22} & \color{red} \beta \ a_{23} \\
    \color{red} \beta \ a_{31} & \color{red} \beta \ a_{32} & \color{red} \beta \ a_{33} 
    \end{bmatrix}
    \ \ \ \ \
    \implies
    \beta \textbf{|A|} = \beta^{n} |\textbf{A}|
    $

- If $ \textbf{A} $ is an upper or lower triangular matrix, then the determinant is the product of its main-diagonal entries

  $ |\textbf{A}| = a_{11} \ a_{22} \ \cdots \ a_{nn} = \prod \limits_{i=1}^{n} a_{ii} $

    $ 
    \begin{bmatrix}
    a_{11} & 0 & 0 \\
    a_{21} & a_{22} & 0 \\
    a_{31} & a_{32} & a_{33} 
    \end{bmatrix}
    , \ \ \ \ \
    \begin{bmatrix}
    a_{11} & a_{12} & a_{13} \\
    0 & a_{22} & a_{23} \\
    0 & 0 & a_{33} 
    \end{bmatrix}
    \ \ \ \ \
    \implies
    |\textbf{A}| = \prod \limits_{i=1}^{n} a_{ii}
    $  
  

### Determinant with SciPy

In [19]:
# numpy determinant
A = np.array([[4, 1, 7], [6, 5, 9], [2, 6, 7]])

print(sp.linalg.det(A))

82.00000000000001


### Minors and Cofactors

- If $ \textbf{A} $ is a square matrix, then the minor of entry $ \textbf{a}_{ij} $ is denoted by $ \textbf{M}_{ij} $ or $ \textbf{A}(i|j) $ and is defined to be the determinant of the sub-matrix that remains after the $ i^{th} $ row and $ j^{th} $ column are deleted from A.
  
  <br/>
  
    $ 
    \textbf{A} = 
  \begin{bmatrix}
  a_{11} & a_{12} & a_{13} \\
  a_{21} & a_{22} & a_{23} \\
  a_{31} & a_{32} & a_{33} \\ 
  \end{bmatrix}
  \implies 
  M_{ij} = A(1|1) = 
    \begin{vmatrix}
  a_{22} & a_{23} \\
  a_{32} & a_{33}
  \end{vmatrix}
  $

<br/>

- The number $ \textbf{C}_{ij} = (-1)^{i+j}\textbf{M}_{ij} $ is called the cofactor of entry $ \textbf{a}_{ij} $. The matrix formed from the elements $ \textbf{C}_{ij} $ is called the matrix of cofactors

  <br/>

    $ 
    \textbf{C} = 
  \begin{bmatrix}
  M_{11}  & -M_{12} & M_{13} \\
  -M_{21}  & M_{22} & -M_{23} \\
  M_{31}  & -M_{32} & M_{33} \\ 
  \end{bmatrix}
  $

<br/>

- The determinant of any matrix $ \textbf{A} $ can be written as 

  $ |\textbf{A}| = \sum \limits_{i=1}^{n} \textbf{A}_{ij}C_{ij} $


### Diagonal Matrices

If $ \textbf{A} $ is an $ n \times n $ triangular matrix (upper, lower or diagonal), then $ \textbf{|A|} $ is the product of the entries on the main diagonal of the matrix, $ \textbf{|A|} = a_{11} \ a_{22} \ a_{33} \ ... \ a_{nn} $

<br/>
For an upper triangular matrix:

  $ 
  \begin{vmatrix}
  a_{11} & a_{12} & a_{13} & a_{14} \\
  0 & a_{22} & a_{23} & a_{24} \\
  0 & 0 & a_{33} & a_{34} \\
  0 & 0 & 0 & a_{44}
  \end{vmatrix}
  = a_{44}
  \begin{vmatrix}
  a_{11} & a_{12} & a_{13} \\
  0 & a_{22} & a_{23} \\
  0 & 0 & a_{33} 
  \end{vmatrix}
  = a_{44} \ a_{33}
  \begin{vmatrix}
  a_{11} & a_{12} \\
  0 & a_{22} 
  \end{vmatrix}
  = a_{44} \ a_{33} \ a_{22}
  \begin{vmatrix}
  a_{11}
  \end{vmatrix}
  = a_{44} \ a_{33} \ a_{22} \ a_{11}
  $

<br/>
For an lower triangular matrix:

  $ 
  \begin{vmatrix}
  a_{11} & 0 & 0 & 0 \\
  a_{21} & a_{22} & 0 & 0 \\
  a_{31} & a_{32} & a_{33} & 0 \\
  a_{41} & a_{42} & a_{43} & a_{44}
  \end{vmatrix}
  = a_{11}
  \begin{vmatrix}
  a_{22} & 0 & 0 \\
  a_{32} & a_{33} & 0 \\
  a_{42} & a_{43} & a_{44} 
  \end{vmatrix}
  = a_{11} \ a_{22}
  \begin{vmatrix}
  a_{33} & 0 \\
  a_{43} & a_{44} 
  \end{vmatrix}
  = a_{11} \ a_{22} \ a_{33}
  \begin{vmatrix}
  a_{44}
  \end{vmatrix}
  = a_{11} \ a_{22} \ a_{33} \ a_{44}
  $
  
  <br/>
  For a plain diagonal matrix:

  $ 
  \begin{vmatrix}
  a_{11} & 0 & 0 & 0 \\
  0 & a_{22} & 0 & 0 \\
  0 & 0 & a_{33} & 0 \\
  0 & 0 & 0 & a_{44}
  \end{vmatrix}
  = a_{11} \ a_{22} \ a_{33} \ a_{44}
  $
  
